export const statisticalTransactions = [
  {
    transaction_id: "#7200-41453",
    customer_name: "JULIA GHEFIRA RAHMAWATI",
    need_type: "Konsultasi Kunjungan langsung",
    request_date: "2025-07-30",
    main_operator: "Ince Mariyani S.E., M.M.",
    status: "Selesai: 0",
    detail: {
      customer_detail: {
        name: "JULIA GHEFIRA RAHMAWATI",
        email: "gefhira15@gmail.com",
        phone_gender: "089637698837/Perempuan",
        age_education: "21/<= SMA",
        unit: "Pribadi/Lainnya",
      },
      completion_date: "30 Juli 2025",
      onsite_visit_detail: {
        need_type: "Konsultasi",
        request_date: "30 Juli 2025",
        completion_date: "30 Juli 2025",
        operator: "Ince Mariyani S.E., M.M.",
        transaction_status: "selesai",
      },
    },
  },
  {
    transaction_id: "#7200-41452",
    customer_name: "DELLA FITRIANI",
    need_type: "Konsultasi Kunjungan langsung",
    request_date: "2025-07-30",
    main_operator: "Ince Mariyani S.E., M.M.",
    status: "Selesai: 0",
    detail: {
      customer_detail: {
        name: "DELLA FITRIANI",
        email: "dellaf.277@gmail.com",
        phone_gender: "085823719072/Perempuan",
        age_education: "21/<= SMA",
        unit: "Pribadi/Lainnya",
      },
      completion_date: "30 Juli 2025",
      onsite_visit_detail: {
        need_type: "Konsultasi",
        request_date: "30 Juli 2025",
        completion_date: "30 Juli 2025",
        operator: "Ince Mariyani S.E., M.M.",
        transaction_status: "selesai",
      },
    },
  },
  {
    transaction_id: "#7200-41451",
    customer_name: "MIFTAHUL JANNAH",
    need_type: "Konsultasi Kunjungan langsung",
    request_date: "2025-07-30",
    main_operator: "Ince Mariyani S.E., M.M.",
    status: "Selesai: 0",
    detail: {
      customer_detail: {
        name: "MIFTAHUL JANNAH",
        email: "miftahuljannah017103@gmail.com",
        phone_gender: "081523911547/Perempuan",
        age_education: "22/<= SMA",
        unit: "Pribadi/Lainnya",
      },
      completion_date: "30 Juli 2025",
      onsite_visit_detail: {
        need_type: "Konsultasi",
        request_date: "30 Juli 2025",
        completion_date: "30 Juli 2025",
        operator: "Ince Mariyani S.E., M.M.",
        transaction_status: "selesai",
      },
    },
  },
  {
    transaction_id: "#7200-41449",
    customer_name: "NUR SASI KHIRANA ZHARANI",
    need_type: "Konsultasi Kunjungan langsung",
    request_date: "2025-07-30",
    main_operator: "Ince Mariyani S.E., M.M.",
    status: "Selesai: 0",
    detail: {
      customer_detail: {
        name: "NUR SASI KHIRANA ZHARANI",
        email: "nursasi202@gmail.com",
        phone_gender: "085825484583/Perempuan",
        age_education: "21/<= SMA",
        unit: "Pribadi/Lainnya",
      },
      completion_date: "30 Juli 2025",
      onsite_visit_detail: {
        need_type: "Konsultasi",
        request_date: "30 Juli 2025",
        completion_date: "30 Juli 2025",
        operator: "Ince Mariyani S.E., M.M.",
        transaction_status: "selesai",
      },
    },
  },
  {
    transaction_id: "#7200-41407",
    customer_name: "ADE MULYANI",
    need_type: "Konsultasi Kunjungan langsung",
    request_date: "2025-07-29",
    main_operator: "Ince Mariyani S.E., M.M.",
    status: "Selesai: 5",
    detail: {
      customer_detail: {
        name: "ADE MULYANI",
        email: "qubaahmadtakapo@gmail.com",
        phone_gender: "082226669002/Perempuan",
        age_education: "35/S1",
        unit: "Staf Dinas Lingkungan Hidup",
      },
      completion_date: "29 Juli 2025",
      onsite_visit_detail: {
        need_type: "Konsultasi",
        request_date: "29 Juli 2025",
        completion_date: "29 Juli 2025",
        operator: "Ince Mariyani S.E., M.M.",
        transaction_status: "selesai",
      },
    },
  },
  {
    transaction_id: "#7200-41404",
    customer_name: "ARYANINGTYAS BIBTARINI, AMD KEP",
    need_type: "Konsultasi Kunjungan langsung",
    request_date: "2025-07-29",
    main_operator: "Ince Mariyani S.E., M.M.",
    status: "Selesai: 5",
    detail: {
      customer_detail: {
        name: "ARYANINGTYAS BIBTARINI, AMD KEP",
        email: "aryaningtiyas47@gmail.com",
        phone_gender: "082312710234/Perempuan",
        age_education: "43/Diploma (D1/D2/D3)",
        unit: "Pribadi/Lainnya",
      },
      completion_date: "29 Juli 2025",
      onsite_visit_detail: {
        need_type: "Konsultasi",
        request_date: "29 Juli 2025",
        completion_date: "29 Juli 2025",
        operator: "Ince Mariyani S.E., M.M.",
        transaction_status: "selesai",
      },
    },
  },
  {
    transaction_id: "#7200-41376",
    customer_name: "SALMA",
    need_type: "Konsultasi Kunjungan langsung",
    request_date: "2025-07-28",
    main_operator: "Ince Mariyani S.E., M.M.",
    status: "Selesai: 5",
    detail: {
      customer_detail: {
        name: "SALMA",
        email: "salmamaasy23@gmail.com",
        phone_gender: "082259005363/Perempuan",
        age_education: "24/<= SMA",
        unit: "Pribadi/Lainnya",
      },
      completion_date: "28 Juli 2025",
      onsite_visit_detail: {
        need_type: "Konsultasi",
        request_date: "28 Juli 2025",
        completion_date: "28 Juli 2025",
        operator: "Ince Mariyani S.E., M.M.",
        transaction_status: "selesai",
      },
    },
  },
  {
    transaction_id: "#7200-41090",
    customer_name: "Pegawai Teladan",
    need_type: "Konsultasi Kunjungan langsung",
    request_date: "2025-07-16",
    main_operator: "Bahtiar SST",
    status: "Selesai: 0",
    detail: {
      customer_detail: {
        name: "Pegawai Teladan",
        email: "tiarsidik@bps.go.id",
        phone_gender: "08114554557/Laki-laki",
        age_education: "31/S1",
        unit: "BPS Provinsi Sulawesi Tengah",
      },
      completion_date: "16 Juli 2025",
      onsite_visit_detail: {
        need_type: "Konsultasi",
        request_date: "16 Juli 2025",
        completion_date: "16 Juli 2025",
        operator: "Bahtiar SST",
        transaction_status: "selesai",
      },
    },
  },
  {
    transaction_id: "#7200-41013",
    customer_name: "LESMANA",
    need_type: "Konsultasi Kunjungan langsung",
    request_date: "2025-07-14",
    main_operator: "Ince Mariyani S.E., M.M.",
    status: "Selesai: 5",
    detail: {
      customer_detail: {
        name: "LESMANA",
        email: "lesmanalewis71@gmail.com",
        phone_gender: "085256118836/Laki-laki",
        age_education: "25/<= SMA",
        unit: "Pribadi/Lainnya",
      },
      completion_date: "14 Juli 2025",
      onsite_visit_detail: {
        need_type: "Konsultasi",
        request_date: "14 Juli 2025",
        completion_date: "14 Juli 2025",
        operator: "Ince Mariyani S.E., M.M.",
        transaction_status: "selesai",
      },
    },
  },
  {
    transaction_id: "#7200-41011",
    customer_name: "YULFIANA",
    need_type: "Konsultasi Kunjungan langsung",
    request_date: "2025-07-14",
    main_operator: "Ince Mariyani S.E., M.M.",
    status: "Selesai: 5",
    detail: {
      customer_detail: {
        name: "YULFIANA",
        email: "yuullfianaaa@gmail.com",
        phone_gender: "087812231841/Perempuan",
        age_education: "23/<= SMA",
        unit: "Pribadi/Lainnya",
      },
      completion_date: "14 Juli 2025",
      onsite_visit_detail: {
        need_type: "Konsultasi",
        request_date: "14 Juli 2025",
        completion_date: "14 Juli 2025",
        operator: "Ince Mariyani S.E., M.M.",
        transaction_status: "selesai",
      },
    },
  },
  {
    transaction_id: "#7200-41007",
    customer_name: "YULFIANA",
    need_type: "Konsultasi Kunjungan langsung",
    request_date: "2025-07-14",
    main_operator: "Ince Mariyani S.E., M.M.",
    status: "Selesai: 0",
    detail: {
      customer_detail: {
        name: "YULFIANA",
        email: "yuullfianaa@gmail.com",
        phone_gender: "087812231841/Perempuan",
        age_education: "23/<= SMA",
        unit: "Pribadi/Lainnya",
      },
      completion_date: "14 Juli 2025",
      onsite_visit_detail: {
        need_type: "Konsultasi",
        request_date: "14 Juli 2025",
        completion_date: "14 Juli 2025",
        operator: "Ince Mariyani S.E., M.M.",
        transaction_status: "selesai",
      },
    },
  },
  {
    transaction_id: "#7200-40838",
    customer_name: "TONNO MELANGI",
    need_type: "Konsultasi Kunjungan langsung",
    request_date: "2025-07-07",
    main_operator: "Ince Mariyani S.E., M.M.",
    status: "Selesai: 5",
    detail: {
      customer_detail: {
        name: "TONNO MELANGI",
        email: "tonnomelangi829@gmail.com",
        phone_gender: "0852-4492-4244/Laki-laki",
        age_education: "36/S1",
        unit: "Staf Admistrasi Pimpinan Pemerintah Provinsi Sulawesi Tengah",
      },
      completion_date: "07 Juli 2025",
      onsite_visit_detail: {
        need_type: "Konsultasi",
        request_date: "07 Juli 2025",
        completion_date: "07 Juli 2025",
        operator: "Ince Mariyani S.E., M.M.",
        transaction_status: "selesai",
      },
    },
  },
  {
    transaction_id: "#7200-40748",
    customer_name: "RICARDO ANTHONIE",
    need_type: "Konsultasi Kunjungan langsung",
    request_date: "2025-07-02",
    main_operator: "Ince Mariyani S.E., M.M.",
    status: "Selesai: 0",
    detail: {
      customer_detail: {
        name: "RICARDO ANTHONIE",
        email: "richardo.anthonie@gmail.com",
        phone_gender: "085240874741/Laki-laki",
        age_education: "36/S1",
        unit: "Manager PT FIDAC INOVASI",
      },
      completion_date: "02 Juli 2025",
      onsite_visit_detail: {
        need_type: "Konsultasi",
        request_date: "02 Juli 2025",
        completion_date: "02 Juli 2025",
        operator: "Ince Mariyani S.E., M.M.",
        transaction_status: "selesai",
      },
    },
  },
  {
    transaction_id: "#7200-40746",
    customer_name: "ISNAINI AL. QUR'ANA",
    need_type: "Konsultasi Kunjungan langsung",
    request_date: "2025-07-02",
    main_operator: "Ince Mariyani S.E., M.M.",
    status: "Selesai: 5",
    detail: {
      customer_detail: {
        name: "ISNAINI AL. QUR'ANA",
        email: "alquranaisnaini@gmail.com",
        phone_gender: "082236490415/Perempuan",
        age_education: "21/<= SMA",
        unit: "Pribadi/Lainnya",
      },
      completion_date: "02 Juli 2025",
      onsite_visit_detail: {
        need_type: "Konsultasi",
        request_date: "02 Juli 2025",
        completion_date: "02 Juli 2025",
        operator: "Ince Mariyani S.E., M.M.",
        transaction_status: "selesai",
      },
    },
  },
  {
    transaction_id: "#7200-40629",
    customer_name: "Wahyu Zuli Firmanto",
    need_type: "Permintaan Data Layanan Online",
    request_date: "2025-06-26",
    main_operator: "Bahtiar SST",
    status: "Selesai: 5",
    detail: {
      customer_detail: {
        name: "Wahyu Zuli Firmanto",
        email: "wahyu@u.nus.edu",
        phone_gender: "32 Tahun/Laki-laki",
        consumer_segmentation: "Peneliti, Mahasiswa, atau Pribadi Lainnya",
        country_phone: "ID/082118625758",
        average_rating: "4.80",
      },
      completion_date: "26 Jun 25 - 11:03:08 WIB",
      online_service_detail: {
        topic: "#40629 Data Mikro",
        request_deadline: "26 Jun 25/11 Jul 25",
        location_status: "Ladu DN",
        operator: "Bahtiar SST",
        transaction_status: "Selesai",
      },
    },
  },
  {
    transaction_id: "#7200-40563",
    customer_name: "MOH. WAHYU DWI AGUNG",
    need_type: "Konsultasi Kunjungan langsung",
    request_date: "2025-06-24",
    main_operator: "Ince Mariyani S.E., M.M.",
    status: "Selesai: 5",
    detail: {
      customer_detail: {
        name: "MOH. WAHYU DWI AGUNG",
        email: "wahyudwiagung002@gmail.com",
        phone_gender: "082259043417/Laki-laki",
        age_education: "25/<= SMA",
        unit: "Pribadi/Lainnya",
      },
      completion_date: "24 Juni 2025",
      onsite_visit_detail: {
        need_type: "Konsultasi",
        request_date: "24 Juni 2025",
        completion_date: "24 Juni 2025",
        operator: "Ince Mariyani S.E., M.M.",
        transaction_status: "selesai",
      },
    },
  },
  {
    transaction_id: "#7200-40540",
    customer_name: "Nareswari",
    need_type: "Konsultasi Layanan Online",
    request_date: "2025-06-23",
    main_operator: "Bahtiar SST",
    status: "Selesai: 0",
    detail: {
      customer_detail: {
        name: "Nareswari",
        email: "nareswarinh9d@gmail.com",
        phone_gender: "22 Tahun/Perempuan",
        consumer_segmentation: "Peneliti, Mahasiswa, atau Pribadi Lainnya",
        country_phone: "ID/081226220572",
        average_rating: "0.00",
      },
      completion_date: "23 Jun 25 - 15:25:47 WIB",
      online_service_detail: {
        topic: "#40540 Konsultasi",
        request_deadline: "23 Jun 25 / 01 Jul 25",
        tag: "Iklim, Potensi Desa",
        consulation_coverage: "Sulawesi Tengah",
        consultation_type: "Konsultasi Data",
        operator: "Bahtiar SST",
        transaction_status: "Selesai",
      },
    },
  },
  {
    transaction_id: "#7200-40499",
    customer_name: "ALDI KRISTIANTO LISANG",
    need_type: "Konsultasi Kunjungan langsung",
    request_date: "2025-06-23",
    main_operator: "Ince Mariyani S.E., M.M.",
    status: "Selesai: 5",
    detail: {
      customer_detail: {
        name: "ALDI KRISTIANTO LISANG",
        email: "aldikristianto066@gmail.com",
        phone_gender: "082344474859/Laki-laki",
        age_education: "22/<= SMA",
        unit: "Pribadi/Lainnya",
      },
      completion_date: "23 Juni 2025",
      onsite_visit_detail: {
        need_type: "Konsultasi",
        request_date: "23 Juni 2025",
        completion_date: "23 Juni 2025",
        operator: "Ince Mariyani S.E., M.M.",
        transaction_status: "selesai",
      },
    },
  },
  {
    transaction_id: "#7200-40471",
    customer_name: "FAUZAN RAMADHAN ACHMAD",
    need_type: "Konsultasi Kunjungan langsung",
    request_date: "2025-06-20",
    main_operator: "Ince Mariyani S.E., M.M.",
    status: "Selesai: 5",
    detail: {
      customer_detail: {
        name: "FAUZAN RAMADHAN ACHMAD",
        email: "fauzanramadhanachmad@gmail.com",
        phone_gender: "081288809739/Laki-laki",
        age_education: "26/<= SMA",
        unit: "Pribadi/Lainnya",
      },
      completion_date: "20 Juni 2025",
      onsite_visit_detail: {
        need_type: "Konsultasi",
        request_date: "20 Juni 2025",
        completion_date: "20 Juni 2025",
        operator: "Ince Mariyani S.E., M.M.",
        transaction_status: "selesai",
      },
    },
  },
  {
    transaction_id: "#7200-40425",
    customer_name: "Sepia Imelda",
    need_type: "Konsultasi Kunjungan langsung",
    request_date: "2025-06-18",
    main_operator: "Ince Mariyani S.E., M.M.",
    status: "Selesai: 5",
    detail: {
      customer_detail: {
        name: "Sepia Imelda",
        email: "sepiaimelda@gmail.com",
        phone_gender: "082259168490/Perempuan",
        age_education: "22/<= SMA",
        unit: "Pribadi/Lainnya",
      },
      completion_date: "18 Juni 2025",
      onsite_visit_detail: {
        need_type: "Konsultasi",
        request_date: "18 Juni 2025",
        completion_date: "18 Juni 2025",
        operator: "Ince Mariyani S.E., M.M.",
        transaction_status: "selesai",
      },
    },
  },
  {
    transaction_id: "#7200-40270",
    customer_name: "LINTANG HANIFAH",
    need_type: "Konsultasi Kunjungan langsung",
    request_date: "2025-06-12",
    main_operator: "Ince Mariyani S.E., M.M.",
    status: "Selesai: 0",
    detail: {
      customer_detail: {
        name: "LINTANG HANIFAH",
        email: "lintanghanifah34@gmail.com",
        phone_gender: "085338005670/Perempuan",
        age_education: "23/<= SMA",
        unit: "Pribadi/Lainnya",
      },
      completion_date: "12 Juni 2025",
      onsite_visit_detail: {
        need_type: "Konsultasi",
        request_date: "12 Juni 2025",
        completion_date: "12 Juni 2025",
        operator: "Ince Mariyani S.E., M.M.",
        transaction_status: "selesai",
      },
    },
  },
  {
    transaction_id: "#7200-40269",
    customer_name: "HESTI INDRIANI",
    need_type: "Konsultasi Kunjungan langsung",
    request_date: "2025-06-12",
    main_operator: "Ince Mariyani S.E., M.M.",
    status: "Selesai: 0",
    detail: {
      customer_detail: {
        name: "HESTI INDRIANI",
        email: "hestiindriaani@gmail.com",
        phone_gender: "082291139863/Perempuan",
        age_education: "22/<= SMA",
        unit: "Pribadi/Lainnya",
      },
      completion_date: "12 Juni 2025",
      onsite_visit_detail: {
        need_type: "Konsultasi",
        request_date: "12 Juni 2025",
        completion_date: "12 Juni 2025",
        operator: "Ince Mariyani S.E., M.M.",
        transaction_status: "selesai",
      },
    },
  },
  {
    transaction_id: "#7200-40198",
    customer_name: "PUTRI SEPTIANI",
    need_type: "Konsultasi Kunjungan langsung",
    request_date: "2025-06-10",
    main_operator: "Ince Mariyani S.E., M.M.",
    status: "Selesai: 0",
    detail: {
      customer_detail: {
        name: "PUTRI SEPTIANI",
        email: "pvtriiseptiani1997@gmail.com",
        phone_gender: "085966791302/Perempuan",
        age_education: "22/<= SMA",
        unit: "Pribadi/Lainnya",
      },
      completion_date: "10 Juni 2025",
      onsite_visit_detail: {
        need_type: "Konsultasi",
        request_date: "10 Juni 2025",
        completion_date: "10 Juni 2025",
        operator: "Ince Mariyani S.E., M.M.",
        transaction_status: "selesai",
      },
    },
  },
  {
    transaction_id: "#7200-40197",
    customer_name: "NUR AINUN",
    need_type: "Konsultasi Kunjungan langsung",
    request_date: "2025-06-10",
    main_operator: "Ince Mariyani S.E., M.M.",
    status: "Selesai: 0",
    detail: {
      customer_detail: {
        name: "NUR AINUN",
        email: "nrainunrm@gmail.com",
        phone_gender: "085656222317/Perempuan",
        age_education: "22/<= SMA",
        unit: "Pribadi/Lainnya",
      },
      completion_date: "10 Juni 2025",
      onsite_visit_detail: {
        need_type: "Konsultasi",
        request_date: "10 Juni 2025",
        completion_date: "10 Juni 2025",
        operator: "Ince Mariyani S.E., M.M.",
        transaction_status: "selesai",
      },
    },
  },
  {
    transaction_id: "#7200-40056",
    customer_name: "I KOMANG SIRDANATA",
    need_type: "Konsultasi Kunjungan langsung",
    request_date: "2025-06-03",
    main_operator: "Ince Mariyani S.E., M.M.",
    status: "Selesai: 5",
    detail: {
      customer_detail: {
        name: "I KOMANG SIRDANATA",
        email: "sirdanata26@gmail.com",
        phone_gender: "082296403780/Laki-laki",
        age_education: "23/<= SMA",
        unit: "Pribadi/Lainnya",
      },
      completion_date: "03 Juni 2025",
      onsite_visit_detail: {
        need_type: "Konsultasi",
        request_date: "03 Juni 2025",
        completion_date: "03 Juni 2025",
        operator: "Ince Mariyani S.E., M.M.",
        transaction_status: "selesai",
      },
    },
  },
  {
    transaction_id: "#7200-40055",
    customer_name: "DANANG ADHI SATYA",
    need_type: "Konsultasi Kunjungan langsung",
    request_date: "2025-06-03",
    main_operator: "Ince Mariyani S.E., M.M.",
    status: "Selesai: 0",
    detail: {
      customer_detail: {
        name: "DANANG ADHI SATYA",
        email: "adhisatyadanang@gmail.com",
        phone_gender: "085757183995/Laki-laki",
        age_education: "23/<= SMA",
        unit: "Pribadi/Lainnya",
      },
      completion_date: "03 Juni 2025",
      onsite_visit_detail: {
        need_type: "Konsultasi",
        request_date: "03 Juni 2025",
        completion_date: "03 Juni 2025",
        operator: "Ince Mariyani S.E., M.M.",
        transaction_status: "selesai",
      },
    },
  },
  {
    transaction_id: "#7200-40039",
    customer_name: "TIRTA RIANTI",
    need_type: "Konsultasi Kunjungan langsung",
    request_date: "2025-06-02",
    main_operator: "Ince Mariyani S.E., M.M.",
    status: "Selesai: 5",
    detail: {
      customer_detail: {
        name: "TIRTA RIANTI",
        email: "tirtarianti@gmail.com",
        phone_gender: "082293884886/Perempuan",
        age_education: "22/<= SMA",
        unit: "Pribadi/Lainnya",
      },
      completion_date: "02 Juni 2025",
      onsite_visit_detail: {
        need_type: "Konsultasi",
        request_date: "02 Juni 2025",
        completion_date: "02 Juni 2025",
        operator: "Ince Mariyani S.E., M.M.",
        transaction_status: "selesai",
      },
    },
  },
  {
    transaction_id: "#7200-40038",
    customer_name: "Reza Ahmad Musakki",
    need_type: "Konsultasi Kunjungan langsung",
    request_date: "2025-06-02",
    main_operator: "Ince Mariyani S.E., M.M.",
    status: "Selesai: 5",
    detail: {
      customer_detail: {
        name: "Reza Ahmad Musakki",
        email: "rezaahmadmusaki@gmail.com",
        phone_gender: "081358786478/Laki-laki",
        age_education: "25/<= SMA",
        unit: "Pribadi/Lainnya",
      },
      completion_date: "02 Juni 2025",
      onsite_visit_detail: {
        need_type: "Konsultasi",
        request_date: "02 Juni 2025",
        completion_date: "02 Juni 2025",
        operator: "Ince Mariyani S.E., M.M.",
        transaction_status: "selesai",
      },
    },
  },
  {
    transaction_id: "#7200-40027",
    customer_name: "ASWAR",
    need_type: "Konsultasi Kunjungan langsung",
    request_date: "2025-06-02",
    main_operator: "Bahtiar SST",
    status: "Selesai: 0",
    detail: {
      customer_detail: {
        name: "ASWAR",
        email: "aswarganteng@gmail.com",
        phone_gender: "085136693670/Laki-laki",
        age_education: "22/<= SMA",
        unit: "Pribadi/Lainnya",
      },
      completion_date: "02 Juni 2025",
      onsite_visit_detail: {
        need_type: "Konsultasi",
        request_date: "02 Juni 2025",
        completion_date: "02 Juni 2025",
        operator: "Bahtiar SST",
        transaction_status: "selesai",
      },
    },
  },
  {
    transaction_id: "#7200-40026",
    customer_name: "MAGFIRAH",
    need_type: "Konsultasi Kunjungan langsung",
    request_date: "2025-06-02",
    main_operator: "Bahtiar SST",
    status: "Selesai: 5",
    detail: {
      customer_detail: {
        name: "MAGFIRAH",
        email: "magfirahfirahh@gmail.com",
        phone_gender: "082321300337/Perempuan",
        age_education: "22/<= SMA",
        unit: "Pribadi/Lainnya",
      },
      completion_date: "02 Juni 2025",
      onsite_visit_detail: {
        need_type: "Konsultasi",
        request_date: "02 Juni 2025",
        completion_date: "02 Juni 2025",
        operator: "Bahtiar SST",
        transaction_status: "selesai",
      },
    },
  },
  {
    transaction_id: "#7200-40025",
    customer_name: "MOHAMAD NAZMUL",
    need_type: "Konsultasi Kunjungan langsung",
    request_date: "2025-06-02",
    main_operator: "Bahtiar SST",
    status: "Selesai: 5",
    detail: {
      customer_detail: {
        name: "MOHAMAD NAZMUL",
        email: "kabilasasigi46@gmail.com",
        phone_gender: "081527150965/Laki-laki",
        age_education: "23/<= SMA",
        unit: "Pribadi/Lainnya",
      },
      completion_date: "02 Juni 2025",
      onsite_visit_detail: {
        need_type: "Konsultasi",
        request_date: "02 Juni 2025",
        completion_date: "02 Juni 2025",
        operator: "Bahtiar SST",
        transaction_status: "selesai",
      },
    },
  },
  {
    transaction_id: "#7200-40017",
    customer_name: "Reza Ahmad Musakki",
    need_type: "Permintaan Data Kunjungan langsung",
    request_date: "2025-06-02",
    main_operator: "Ince Mariyani S.E., M.M.",
    status: "Batal",
    detail: {
      customer_detail: {
        name: "Reza Ahmad Musakki",
        email: "rezaahmadmusaki@gmail.com",
        phone_gender: "081358786478/Laki-laki",
        age_education: "25/<= SMA",
        unit: "Pribadi/Lainnya",
      },
      completion_date: null,
      onsite_visit_detail: {
        need_type: "Permintaan Data",
        request_date: "02 Juni 2025",
        operator: "Ince Mariyani S.E., M.M.",
        transaction_status: "batal",
      },
    },
  },
  {
    transaction_id: "#7200-39959",
    customer_name: "Nur Syafriyati Yuniarti",
    need_type: "Permintaan Data Layanan Online",
    request_date: "2025-05-28",
    main_operator: "Bahtiar SST",
    status: "Selesai: 0",
    detail: {
      customer_detail: {
        name: "Nur Syafriyati Yuniarti",
        email: "syafriyatiyuniarti18@gmail.com",
        phone_gender: "28 Tahun/Perempuan",
        consumer_segmentation: "Peneliti, Mahasiswa, atau Pribadi Lainnya",
        country_phone: "ID/085283127272",
        average_rating: "4.00",
      },
      completion_date: "28 Mei 25 - 10:14:44 WIB",
      online_service_detail: {
        topic: "#39959 Data Mikro",
        request_deadline: "28 Mei 25/17 Jun 25",
        location_status: "Ladu DN",
        operator: "Bahtiar SST",
        transaction_status: "Selesai",
      },
    },
  },
  {
    transaction_id: "#7200-39929",
    customer_name: "Royan Al Qois",
    need_type: "Konsultasi Kunjungan langsung",
    request_date: "2025-05-27",
    main_operator: "Ince Mariyani S.E., M.M.",
    status: "Selesai: 0",
    detail: {
      customer_detail: {
        name: "Royan Al Qois",
        email: "alqoisroyan@gmail.com",
        phone_gender: "082290471162/Laki-laki",
        age_education: "23/<= SMA",
        unit: "Pribadi/Lainnya",
      },
      completion_date: "28 Mei 2025",
      onsite_visit_detail: {
        need_type: "Konsultasi",
        request_date: "27 Mei 2025",
        completion_date: "28 Mei 2025",
        operator: "Ince Mariyani S.E., M.M.",
        transaction_status: "selesai",
      },
    },
  },
  {
    transaction_id: "#7200-39918",
    customer_name: "SUAIBAH OKTAVIANI",
    need_type: "Konsultasi Kunjungan langsung",
    request_date: "2025-05-27",
    main_operator: "Bahtiar SST",
    status: "Selesai: 0",
    detail: {
      customer_detail: {
        name: "SUAIBAH OKTAVIANI",
        email: "aibahoktaviani@gmail.com",
        phone_gender: "0877765463727/Perempuan",
        age_education: "23/<= SMA",
        unit: "Pribadi/Lainnya",
      },
      completion_date: "28 Mei 2025",
      onsite_visit_detail: {
        need_type: "Konsultasi",
        request_date: "27 Mei 2025",
        completion_date: "28 Mei 2025",
        operator: "Bahtiar SST",
        transaction_status: "selesai",
      },
    },
  },
  {
    transaction_id: "#7200-39917",
    customer_name: "ANDAR",
    need_type: "Konsultasi Kunjungan langsung",
    request_date: "2025-05-27",
    main_operator: "Bahtiar SST",
    status: "Selesai: 0",
    detail: {
      customer_detail: {
        name: "ANDAR",
        email: "adrbns6@gmail.com",
        phone_gender: "082292520745/Laki-laki",
        age_education: "23/<= SMA",
        unit: "Pribadi/Lainnya",
      },
      completion_date: "28 Mei 2025",
      onsite_visit_detail: {
        need_type: "Konsultasi",
        request_date: "27 Mei 2025",
        completion_date: "28 Mei 2025",
        operator: "Bahtiar SST",
        transaction_status: "selesai",
      },
    },
  },
  {
    transaction_id: "#7200-39912",
    customer_name: "Nur Syafriyati Yuniarti",
    need_type: "Konsultasi Kunjungan langsung",
    request_date: "2025-05-27",
    main_operator: "Ince Mariyani S.E., M.M.",
    status: "Selesai: 5",
    detail: {
      customer_detail: {
        name: "Nur Syafriyati Yuniarti",
        email: "syafriyatiyuniarti18@gmail.com",
        phone_gender: "085283127272/Perempuan",
        age_education: "28/S1",
        unit: "Pribadi/Lainnya",
      },
      completion_date: "28 Mei 2025",
      onsite_visit_detail: {
        need_type: "Konsultasi",
        request_date: "27 Mei 2025",
        completion_date: "28 Mei 2025",
        operator: "Ince Mariyani S.E., M.M.",
        transaction_status: "selesai",
      },
    },
  },
  {
    transaction_id: "#7200-39793",
    customer_name: "NURYANA HAPRIN",
    need_type: "Konsultasi Kunjungan langsung",
    request_date: "2025-05-22",
    main_operator: "Ince Mariyani S.E., M.M.",
    status: "Selesai: 0",
    detail: {
      customer_detail: {
        name: "NURYANA HAPRIN",
        email: "yanadjachmad@gmail.com",
        phone_gender: "085256012444/Perempuan",
        age_education: "35/S2",
        unit: "Pribadi/Lainnya",
      },
      completion_date: "23 Mei 2025",
      onsite_visit_detail: {
        need_type: "Konsultasi",
        request_date: "22 Mei 2025",
        completion_date: "23 Mei 2025",
        operator: "Ince Mariyani S.E., M.M.",
        transaction_status: "selesai",
      },
    },
  },
  {
    transaction_id: "#7200-39753",
    customer_name: "INDA SRI WAHYU N. NASER",
    need_type: "Konsultasi Kunjungan langsung",
    request_date: "2025-05-21",
    main_operator: "Ince Mariyani S.E., M.M.",
    status: "Selesai: 0",
    detail: {
      customer_detail: {
        name: "INDA SRI WAHYU N. NASER",
        email: "indasriwahyu123@gmail.com",
        phone_gender: "082271345814/Perempuan",
        age_education: "24/<= SMA",
        unit: "Pribadi/Lainnya",
      },
      completion_date: "22 Mei 2025",
      onsite_visit_detail: {
        need_type: "Konsultasi",
        request_date: "21 Mei 2025",
        completion_date: "22 Mei 2025",
        operator: "Ince Mariyani S.E., M.M.",
        transaction_status: "selesai",
      },
    },
  },
  {
    transaction_id: "#7200-39751",
    customer_name: "ENDA GUNAWAN",
    need_type: "Konsultasi Kunjungan langsung",
    request_date: "2025-05-21",
    main_operator: "Ince Mariyani S.E., M.M.",
    status: "Selesai: 0",
    detail: {
      customer_detail: {
        name: "ENDA GUNAWAN",
        email: "bn124243@gmail.com",
        phone_gender: "083835569549/Laki-laki",
        age_education: "23/<= SMA",
        unit: "Pribadi/Lainnya",
      },
      completion_date: "22 Mei 2025",
      onsite_visit_detail: {
        need_type: "Konsultasi",
        request_date: "21 Mei 2025",
        completion_date: "22 Mei 2025",
        operator: "Ince Mariyani S.E., M.M.",
        transaction_status: "selesai",
      },
    },
  },
  {
    transaction_id: "#7200-39750",
    customer_name: "PATRI WULANDARI",
    need_type: "Konsultasi Kunjungan langsung",
    request_date: "2025-05-21",
    main_operator: "Ince Mariyani S.E., M.M.",
    status: "Selesai: 0",
    detail: {
      customer_detail: {
        name: "PATRI WULANDARI",
        email: "patriwulandarimm@gmail.com",
        phone_gender: "082292688220/Perempuan",
        age_education: "24/<= SMA",
        unit: "Pribadi/Lainnya",
      },
      completion_date: "22 Mei 2025",
      onsite_visit_detail: {
        need_type: "Konsultasi",
        request_date: "21 Mei 2025",
        completion_date: "22 Mei 2025",
        operator: "Ince Mariyani S.E., M.M.",
        transaction_status: "selesai",
      },
    },
  },
  {
    transaction_id: "#7200-39741",
    customer_name: "HUSA EVA AMAL",
    need_type: "Konsultasi Kunjungan langsung",
    request_date: "2025-05-21",
    main_operator: "Ince Mariyani S.E., M.M.",
    status: "Selesai: 0",
    detail: {
      customer_detail: {
        name: "HUSA EVA AMAL",
        email: "husaevaa03@gmail.com",
        phone_gender: "081355656968/Perempuan",
        age_education: "22/<= SMA",
        unit: "Pribadi/Lainnya",
      },
      completion_date: "22 Mei 2025",
      onsite_visit_detail: {
        need_type: "Konsultasi",
        request_date: "21 Mei 2025",
        completion_date: "22 Mei 2025",
        operator: "Ince Mariyani S.E., M.M.",
        transaction_status: "selesai",
      },
    },
  },
  {
    transaction_id: "#7200-39738",
    customer_name: "SAINUDDIN",
    need_type: "Konsultasi Kunjungan langsung",
    request_date: "2025-05-21",
    main_operator: "Ince Mariyani S.E., M.M.",
    status: "Selesai: 0",
    detail: {
      customer_detail: {
        name: "SAINUDDIN",
        email: "sainuddin1110@gmail.com",
        phone_gender: "082350293464/Laki-laki",
        age_education: "23/<= SMA",
        unit: "Pribadi/Lainnya",
      },
      completion_date: "22 Mei 2025",
      onsite_visit_detail: {
        need_type: "Konsultasi",
        request_date: "21 Mei 2025",
        completion_date: "22 Mei 2025",
        operator: "Ince Mariyani S.E., M.M.",
        transaction_status: "selesai",
      },
    },
  },
  {
    transaction_id: "#7200-39559",
    customer_name: "NI KOMANG SITI PARWAH",
    need_type: "Konsultasi Kunjungan langsung",
    request_date: "2025-05-15",
    main_operator: "Ince Mariyani S.E., M.M.",
    status: "Selesai: 0",
    detail: {
      customer_detail: {
        name: "NI KOMANG SITI PARWAH",
        email: "sitiparwati93@gmail.com",
        phone_gender: "082239712248/Perempuan",
        age_education: "21/<= SMA",
        unit: "Pribadi/Lainnya",
      },
      completion_date: "15 Mei 2025",
      onsite_visit_detail: {
        need_type: "Konsultasi",
        request_date: "15 Mei 2025",
        completion_date: "15 Mei 2025",
        operator: "Ince Mariyani S.E., M.M.",
        transaction_status: "selesai",
      },
    },
  },
  {
    transaction_id: "#7200-39423",
    customer_name: "NIZAR AZ NAZHRO HADJU",
    need_type: "Konsultasi Kunjungan langsung",
    request_date: "2025-05-09",
    main_operator: "Ince Mariyani S.E., M.M.",
    status: "Selesai: 0",
    detail: {
      customer_detail: {
        name: "NIZAR AZ NAZHRO HADJU",
        email: "nizarhadju@gmail.com",
        phone_gender: "081250442190/Laki-laki",
        age_education: "24/<= SMA",
        unit: "Pribadi/Lainnya",
      },
      completion_date: "10 Mei 2025",
      onsite_visit_detail: {
        need_type: "Konsultasi",
        request_date: "09 Mei 2025",
        completion_date: "10 Mei 2025",
        operator: "Ince Mariyani S.E., M.M.",
        transaction_status: "selesai",
      },
    },
  },
  {
    transaction_id: "#7200-39393",
    customer_name: "ABDIEL TOEDJE",
    need_type: "Konsultasi Kunjungan langsung",
    request_date: "2025-05-08",
    main_operator: "Ince Mariyani S.E., M.M.",
    status: "Selesai: 0",
    detail: {
      customer_detail: {
        name: "ABDIEL TOEDJE",
        email: "abdieltoedje86@gmail.com",
        phone_gender: "082189010011/Laki-laki",
        age_education: "39/S1",
        unit: "Pribadi/Lainnya",
      },
      completion_date: "09 Mei 2025",
      onsite_visit_detail: {
        need_type: "Konsultasi",
        request_date: "08 Mei 2025",
        completion_date: "09 Mei 2025",
        operator: "Ince Mariyani S.E., M.M.",
        transaction_status: "selesai",
      },
    },
  },
  {
    transaction_id: "#7200-39362",
    customer_name: "FATMAWATI",
    need_type: "Konsultasi Kunjungan langsung",
    request_date: "2025-05-08",
    main_operator: "Ince Mariyani S.E., M.M.",
    status: "Selesai: 0",
    detail: {
      customer_detail: {
        name: "FATMAWATI",
        email: "fatmawatiahg@gmail.com",
        phone_gender: "085946755558/Perempuan",
        age_education: "25/S1",
        unit: "Pribadi/Lainnya",
      },
      completion_date: "09 Mei 2025",
      onsite_visit_detail: {
        need_type: "Konsultasi",
        request_date: "08 Mei 2025",
        completion_date: "09 Mei 2025",
        operator: "Ince Mariyani S.E., M.M.",
        transaction_status: "selesai",
      },
    },
  },
  {
    transaction_id: "#7200-39273",
    customer_name: "TRIWAHYUNINGTYAS",
    need_type: "Konsultasi Kunjungan langsung",
    request_date: "2025-05-06",
    main_operator: "Ince Mariyani S.E., M.M.",
    status: "Selesai: 0",
    detail: {
      customer_detail: {
        name: "TRIWAHYUNINGTYAS",
        email: "wahyuningtyastri976@gmail.com",
        phone_gender: "085247184912/Perempuan",
        age_education: "21/<= SMA",
        unit: "Pribadi/Lainnya",
      },
      completion_date: "07 Mei 2025",
      onsite_visit_detail: {
        need_type: "Konsultasi",
        request_date: "06 Mei 2025",
        completion_date: "07 Mei 2025",
        operator: "Ince Mariyani S.E., M.M.",
        transaction_status: "selesai",
      },
    },
  },
  {
    transaction_id: "#7200-39269",
    customer_name: "KARTRIKA AMALIA",
    need_type: "Konsultasi Kunjungan langsung",
    request_date: "2025-05-06",
    main_operator: "Ince Mariyani S.E., M.M.",
    status: "Selesai: 0",
    detail: {
      customer_detail: {
        name: "KARTRIKA AMALIA",
        email: "kartikaamaliaeca@gmail.com",
        phone_gender: "082228923492/Perempuan",
        age_education: "22/<= SMA",
        unit: "Pribadi/Lainnya",
      },
      completion_date: "07 Mei 2025",
      onsite_visit_detail: {
        need_type: "Konsultasi",
        request_date: "06 Mei 2025",
        completion_date: "07 Mei 2025",
        operator: "Ince Mariyani S.E., M.M.",
        transaction_status: "selesai",
      },
    },
  },
  {
    transaction_id: "#7200-39229",
    customer_name: "INDA SRI WAHYU N. NASER",
    need_type: "Konsultasi Kunjungan langsung",
    request_date: "2025-05-05",
    main_operator: "Ince Mariyani S.E., M.M.",
    status: "Selesai: 0",
    detail: {
      customer_detail: {
        name: "INDA SRI WAHYU N. NASER",
        email: "indasriwahyu123@gmail.com",
        phone_gender: "082271345814/Perempuan",
        age_education: "24/<= SMA",
        unit: "Pribadi/Lainnya",
      },
      completion_date: "06 Mei 2025",
      onsite_visit_detail: {
        need_type: "Konsultasi",
        request_date: "05 Mei 2025",
        completion_date: "06 Mei 2025",
        operator: "Ince Mariyani S.E., M.M.",
        transaction_status: "selesai",
      },
    },
  },
  {
    transaction_id: "#7200-39170",
    customer_name: "RINI PUSPITA SARI",
    need_type: "Konsultasi Kunjungan langsung",
    request_date: "2025-05-02",
    main_operator: "Ince Mariyani S.E., M.M.",
    status: "Selesai: 0",
    detail: {
      customer_detail: {
        name: "RINI PUSPITA SARI",
        email: "rinikasema@gmail.com",
        phone_gender: "082191937296/Perempuan",
        age_education: "42/S2",
        unit: "Pribadi/Lainnya",
      },
      completion_date: "03 Mei 2025",
      onsite_visit_detail: {
        need_type: "Konsultasi",
        request_date: "02 Mei 2025",
        completion_date: "03 Mei 2025",
        operator: "Ince Mariyani S.E., M.M.",
        transaction_status: "selesai",
      },
    },
  },
  {
    transaction_id: "#7200-39139",
    customer_name: "Sinta Simatupang",
    need_type: "Permintaan Data Layanan Online",
    request_date: "2025-04-30",
    main_operator: "Bahtiar SST",
    status: "Selesai: 5",
    detail: {
      customer_detail: {
        name: "Sinta Simatupang",
        email: "sinta_adelina@adraindonesia.org",
        phone_gender: "49 Tahun/Perempuan",
        consumer_segmentation: "Lembaga Internasional/Perwakilan Negara Asing",
        country_phone: "ID/081341005904",
        average_rating: "5.00",
      },
      completion_date: "30 Apr 25 - 17:51:02 WIB",
      online_service_detail: {
        topic: "#39139 Data Mikro",
        request_deadline: "30 Apr 25/19 Mei 25",
        location_status: "Ladu DN",
        operator: "Bahtiar SST",
        transaction_status: "Selesai",
      },
    },
  },
  {
    transaction_id: "#7200-39133",
    customer_name: "Reza Ahmad Musakki",
    need_type: "Konsultasi Layanan Online",
    request_date: "2025-04-30",
    main_operator: "Bahtiar SST",
    status: "Batal",
    detail: {
      customer_detail: {
        name: "Reza Ahmad Musakki",
        email: "rezaahmadmusaki@gmail.com",
        phone_gender: "25 Tahun/Laki-laki",
        consumer_segmentation: "Peneliti, Mahasiswa, atau Pribadi Lainnya",
        country_phone: "ID/081358786478",
        average_rating: "5.00",
      },
      completion_date: "30 Apr 25 - 14:27:57 WIB",
      online_service_detail: {
        topic: "#39133 Konsultasi",
        request_deadline: "30 Apr 25 / 08 Mei 25",
        tag: "Kependudukan, Pendidikan, Konsumsi dan Pengeluaran, Lainnya",
        consulation_coverage: "Sulawesi Tengah",
        consultation_type: "Konsultasi Data",
        operator: "Bahtiar SST",
        transaction_status: "Proses",
      },
    },
  },
  {
    transaction_id: "#7200-39027",
    customer_name: "ZULHULAYFA ZIDRATUN",
    need_type: "Konsultasi Kunjungan langsung",
    request_date: "2025-04-28",
    main_operator: "Ince Mariyani S.E., M.M.",
    status: "Selesai: 0",
    detail: {
      customer_detail: {
        name: "ZULHULAYFA ZIDRATUN",
        email: "zulhulayfazidratun1212@gmail.com",
        phone_gender: "081523711180/Perempuan",
        age_education: "22/<= SMA",
        unit: "Pribadi/Lainnya",
      },
      completion_date: "29 April 2025",
      onsite_visit_detail: {
        need_type: "Konsultasi",
        request_date: "28 April 2025",
        completion_date: "29 April 2025",
        operator: "Ince Mariyani S.E., M.M.",
        transaction_status: "selesai",
      },
    },
  },
  {
    transaction_id: "#7200-39026",
    customer_name: "BUNG TOMO",
    need_type: "Konsultasi Kunjungan langsung",
    request_date: "2025-04-28",
    main_operator: "Ince Mariyani S.E., M.M.",
    status: "Selesai: 0",
    detail: {
      customer_detail: {
        name: "BUNG TOMO",
        email: "bungtomo0902@gmail.com",
        phone_gender: "085757465663/Laki-laki",
        age_education: "23/<= SMA",
        unit: "Pribadi/Lainnya",
      },
      completion_date: "29 April 2025",
      onsite_visit_detail: {
        need_type: "Konsultasi",
        request_date: "28 April 2025",
        completion_date: "29 April 2025",
        operator: "Ince Mariyani S.E., M.M.",
        transaction_status: "selesai",
      },
    },
  },
  {
    transaction_id: "#7200-38992",
    customer_name: "DWI WINARDI",
    need_type: "Konsultasi Kunjungan langsung",
    request_date: "2025-04-25",
    main_operator: "Ince Mariyani S.E., M.M.",
    status: "Selesai: 0",
    detail: {
      customer_detail: {
        name: "DWI WINARDI",
        email: "dwi.binkarsdm@gmail.com",
        phone_gender: "0852411380005/Laki-laki",
        age_education: "35/S2",
        unit: "Kepala Biro. SDM Polda Sulteng Polda Sulawesi Tengah",
      },
      completion_date: "26 April 2025",
      onsite_visit_detail: {
        need_type: "Konsultasi",
        request_date: "25 April 2025",
        completion_date: "26 April 2025",
        operator: "Ince Mariyani S.E., M.M.",
        transaction_status: "selesai",
      },
    },
  },
  {
    transaction_id: "#7200-38926",
    customer_name: "Siiti Marhama",
    need_type: "Konsultasi Kunjungan langsung",
    request_date: "2025-04-23",
    main_operator: "Ince Mariyani S.E., M.M.",
    status: "Selesai: 0",
    detail: {
      customer_detail: {
        name: "Siiti Marhama",
        email: "sitimarhama255@gmail.com",
        phone_gender: "082296540631/Perempuan",
        age_education: "21/<= SMA",
        unit: "Pribadi/Lainnya",
      },
      completion_date: "24 April 2025",
      onsite_visit_detail: {
        need_type: "Konsultasi",
        request_date: "23 April 2025",
        completion_date: "24 April 2025",
        operator: "Ince Mariyani S.E., M.M.",
        transaction_status: "selesai",
      },
    },
  },
  {
    transaction_id: "#7200-38923",
    customer_name: "YENITA AMELIA IKA PUTRI S.TR.STAT.",
    need_type: "Konsultasi Kunjungan langsung",
    request_date: "2025-04-23",
    main_operator: "Ince Mariyani S.E., M.M.",
    status: "Selesai: 0",
    detail: {
      customer_detail: {
        name: "YENITA AMELIA IKA PUTRI S.TR.STAT.",
        email: "yenitamelia@bps.go.id",
        phone_gender: "/Perempuan",
        age_education: "25/S1",
        unit: "Pribadi/Lainnya",
      },
      completion_date: "24 April 2025",
      onsite_visit_detail: {
        need_type: "Konsultasi",
        request_date: "23 April 2025",
        completion_date: "24 April 2025",
        operator: "Ince Mariyani S.E., M.M.",
        transaction_status: "selesai",
      },
    },
  },
  {
    transaction_id: "#7200-38922",
    customer_name: "PINEHAS DANU ARVITO",
    need_type: "Konsultasi Kunjungan langsung",
    request_date: "2025-04-23",
    main_operator: "Ince Mariyani S.E., M.M.",
    status: "Selesai: 0",
    detail: {
      customer_detail: {
        name: "PINEHAS DANU ARVITO",
        email: "pinehas_danu@bi.go.id",
        phone_gender: "085779571732/Laki-laki",
        age_education: "28/S1",
        unit: "Karyawan Bank Indonesia",
      },
      completion_date: "24 April 2025",
      onsite_visit_detail: {
        need_type: "Konsultasi",
        request_date: "23 April 2025",
        completion_date: "24 April 2025",
        operator: "Ince Mariyani S.E., M.M.",
        transaction_status: "selesai",
      },
    },
  },
  {
    transaction_id: "#7200-38916",
    customer_name: "MUSDALIFA",
    need_type: "Konsultasi Kunjungan langsung",
    request_date: "2025-04-23",
    main_operator: "Ince Mariyani S.E., M.M.",
    status: "Selesai: 0",
    detail: {
      customer_detail: {
        name: "MUSDALIFA",
        email: "mdalifa025@gmail.com",
        phone_gender: "082271066515/Perempuan",
        age_education: "23/<= SMA",
        unit: "Pribadi/Lainnya",
      },
      completion_date: "24 April 2025",
      onsite_visit_detail: {
        need_type: "Konsultasi",
        request_date: "23 April 2025",
        completion_date: "24 April 2025",
        operator: "Ince Mariyani S.E., M.M.",
        transaction_status: "selesai",
      },
    },
  },
  {
    transaction_id: "#7200-38733",
    customer_name: "FARADIBA",
    need_type: "Konsultasi Kunjungan langsung",
    request_date: "2025-04-15",
    main_operator: "Ince Mariyani S.E., M.M.",
    status: "Selesai: 0",
    detail: {
      customer_detail: {
        name: "FARADIBA",
        email: "faradiba123@gmail.com",
        phone_gender: "085396745729/Perempuan",
        age_education: "26/<= SMA",
        unit: "Pribadi/Lainnya",
      },
      completion_date: "16 April 2025",
      onsite_visit_detail: {
        need_type: "Konsultasi",
        request_date: "15 April 2025",
        completion_date: "16 April 2025",
        operator: "Ince Mariyani S.E., M.M.",
        transaction_status: "selesai",
      },
    },
  },
  {
    transaction_id: "#7200-38544",
    customer_name: "SITI ZAHRA",
    need_type: "Konsultasi Kunjungan langsung",
    request_date: "2025-03-27",
    main_operator: "Ince Mariyani S.E., M.M.",
    status: "Selesai: 0",
    detail: {
      customer_detail: {
        name: "SITI ZAHRA",
        email: "zahracici.diabbb@gmail.com",
        phone_gender: "085252342030/Perempuan",
        age_education: "20/<= SMA",
        unit: "Pribadi/Lainnya",
      },
      completion_date: "28 Maret 2025",
      onsite_visit_detail: {
        need_type: "Konsultasi",
        request_date: "27 Maret 2025",
        completion_date: "28 Maret 2025",
        operator: "Ince Mariyani S.E., M.M.",
        transaction_status: "selesai",
      },
    },
  },
  {
    transaction_id: "#7200-38543",
    customer_name: "UMIRA",
    need_type: "Konsultasi Kunjungan langsung",
    request_date: "2025-03-27",
    main_operator: "Ince Mariyani S.E., M.M.",
    status: "Selesai: 0",
    detail: {
      customer_detail: {
        name: "UMIRA",
        email: "amirasabang74@gmail.com",
        phone_gender: "082296995855/Perempuan",
        age_education: "21/<= SMA",
        unit: "Pribadi/Lainnya",
      },
      completion_date: "28 Maret 2025",
      onsite_visit_detail: {
        need_type: "Konsultasi",
        request_date: "27 Maret 2025",
        completion_date: "28 Maret 2025",
        operator: "Ince Mariyani S.E., M.M.",
        transaction_status: "selesai",
      },
    },
  },
  {
    transaction_id: "#7200-38542",
    customer_name: "MAGFIRAH ATSARI AYU",
    need_type: "Konsultasi Kunjungan langsung",
    request_date: "2025-03-27",
    main_operator: "Ince Mariyani S.E., M.M.",
    status: "Selesai: 0",
    detail: {
      customer_detail: {
        name: "MAGFIRAH ATSARI AYU",
        email: "atsarifira@gmail.com",
        phone_gender: "082271677986/Perempuan",
        age_education: "21/<= SMA",
        unit: "Pribadi/Lainnya",
      },
      completion_date: "28 Maret 2025",
      onsite_visit_detail: {
        need_type: "Konsultasi",
        request_date: "27 Maret 2025",
        completion_date: "28 Maret 2025",
        operator: "Ince Mariyani S.E., M.M.",
        transaction_status: "selesai",
      },
    },
  },
  {
    transaction_id: "#7200-38541",
    customer_name: "RIA RESKITA",
    need_type: "Konsultasi Kunjungan langsung",
    request_date: "2025-03-27",
    main_operator: "Ince Mariyani S.E., M.M.",
    status: "Selesai: 0",
    detail: {
      customer_detail: {
        name: "RIA RESKITA",
        email: "riareskita97@gmail.com",
        phone_gender: "082349611859/Perempuan",
        age_education: "23/<= SMA",
        unit: "Pribadi/Lainnya",
      },
      completion_date: "28 Maret 2025",
      onsite_visit_detail: {
        need_type: "Konsultasi",
        request_date: "27 Maret 2025",
        completion_date: "28 Maret 2025",
        operator: "Ince Mariyani S.E., M.M.",
        transaction_status: "selesai",
      },
    },
  },
  {
    transaction_id: "#7200-38528",
    customer_name: "AYU SAVITRI",
    need_type: "Konsultasi Kunjungan langsung",
    request_date: "2025-03-27",
    main_operator: "Ince Mariyani S.E., M.M.",
    status: "Selesai: 0",
    detail: {
      customer_detail: {
        name: "AYU SAVITRI",
        email: "savitria719@gmail.com",
        phone_gender: "085272922180/Perempuan",
        age_education: "22/<= SMA",
        unit: "Pribadi/Lainnya",
      },
      completion_date: "28 Maret 2025",
      onsite_visit_detail: {
        need_type: "Konsultasi",
        request_date: "27 Maret 2025",
        completion_date: "28 Maret 2025",
        operator: "Ince Mariyani S.E., M.M.",
        transaction_status: "selesai",
      },
    },
  },
  {
    transaction_id: "#7200-38527",
    customer_name: "AYU SAVITRI",
    need_type: "Konsultasi Kunjungan langsung",
    request_date: "2025-03-27",
    main_operator: "Ince Mariyani S.E., M.M.",
    status: "Selesai: 0",
    detail: {
      customer_detail: {
        name: "AYU SAVITRI",
        email: "savitria719@gmail.com",
        phone_gender: "085272922180/Perempuan",
        age_education: "22/<= SMA",
        unit: "Pribadi/Lainnya",
      },
      completion_date: "28 Maret 2025",
      onsite_visit_detail: {
        need_type: "Konsultasi",
        request_date: "27 Maret 2025",
        completion_date: "28 Maret 2025",
        operator: "Ince Mariyani S.E., M.M.",
        transaction_status: "selesai",
      },
    },
  },
  {
    transaction_id: "#7200-38378",
    customer_name: "MOH. ALDI",
    need_type: "Konsultasi Kunjungan langsung",
    request_date: "2025-03-19",
    main_operator: "Ince Mariyani S.E., M.M.",
    status: "Selesai: 0",
    detail: {
      customer_detail: {
        name: "MOH. ALDI",
        email: "muhaldi157424@gmail.com",
        phone_gender: "085369357411/Laki-laki",
        age_education: "22/<= SMA",
        unit: "Pribadi/Lainnya",
      },
      completion_date: "20 Maret 2025",
      onsite_visit_detail: {
        need_type: "Konsultasi",
        request_date: "19 Maret 2025",
        completion_date: "20 Maret 2025",
        operator: "Ince Mariyani S.E., M.M.",
        transaction_status: "selesai",
      },
    },
  },
  {
    transaction_id: "#7200-38133",
    customer_name: "SYAIFUL BAHRI",
    need_type: "Konsultasi Kunjungan langsung",
    request_date: "2025-03-11",
    main_operator: "Ince Mariyani S.E., M.M.",
    status: "Selesai: 0",
    detail: {
      customer_detail: {
        name: "SYAIFUL BAHRI",
        email: "syaifulandewa999@gmail.com",
        phone_gender: "082293369949/Laki-laki",
        age_education: "22/<= SMA",
        unit: "Pribadi/Lainnya",
      },
      completion_date: "12 Maret 2025",
      onsite_visit_detail: {
        need_type: "Konsultasi",
        request_date: "11 Maret 2025",
        completion_date: "12 Maret 2025",
        operator: "Ince Mariyani S.E., M.M.",
        transaction_status: "selesai",
      },
    },
  },
  {
    transaction_id: "#7200-38109",
    customer_name: "Darmawati Darwis",
    need_type: "Konsultasi Layanan Online",
    request_date: "2025-03-10",
    main_operator: "Bahtiar SST",
    status: "Selesai: 0",
    detail: {
      customer_detail: {
        name: "Darmawati Darwis",
        email: "puslak484@gmail.com",
        phone_gender: "54 Tahun/Perempuan",
        consumer_segmentation: "Instansi/Lembaga Pemerintah (Pusat/Daerah)",
        country_phone: "ID/085396182907",
        average_rating: "0.00",
      },
      completion_date: "10 Mar 25 - 13:18:53 WIB",
      online_service_detail: {
        topic: "#38109 Konsultasi",
        request_deadline: "10 Mar 25 / 17 Mar 25",
        tag: "input_output",
        consultation_coverage: "Sulawesi Tengah",
        consultation_type: "Data Consultation",
        operator: "Bahtiar SST",
        transaction_status: "Selesai",
      },
    },
  },
  {
    transaction_id: "#7200-37928",
    customer_name: "Annisa Meiva Almasari",
    need_type: "Konsultasi Layanan Online",
    request_date: "2025-03-04",
    main_operator: "Bahtiar SST",
    status: "Selesai: 0",
    detail: {
      customer_detail: {
        name: "Annisa Meiva Almasari",
        email: "annisalmasari03@gmail.com",
        phone_gender: "24 Tahun/Perempuan",
        consumer_segmentation: "Peneliti, Mahasiswa, atau Pribadi Lainnya",
        country_phone: "ID/082146361525",
        average_rating: "0.00",
      },
      completion_date: "04 Mar 25 - 08:28:01 WIB",
      online_service_detail: {
        topic: "#37928 Konsultasi",
        request_deadline: "04 Mar 25 / 11 Mar 25",
        tag: "Pemerintahan, Keuangan, Kemiskinan dan Ketimpangan, Produk Domestik Regional Bruto (Lapangan Usaha), Lainnya",
        consulation_coverage: "Sulawesi Tengah",
        consultation_type: "Konsultasi Data",
        operator: "Bahtiar SST",
        transaction_status: "Selesai",
      },
    },
  },
  {
    transaction_id: "#7200-37927",
    customer_name: "Annisa Meiva Almasari",
    need_type: "Konsultasi Layanan Online",
    request_date: "2025-03-04",
    main_operator: "Admin Sulteng",
    status: "Batal",
    detail: {
      customer_detail: {
        name: "Annisa Meiva Almasari",
        email: "annisalmasari03@gmail.com",
        phone_gender: "24 Tahun/Perempuan",
        consumer_segmentation: "Peneliti, Mahasiswa, atau Pribadi Lainnya",
        country_phone: "ID/082146361525",
        average_rating: "0.00",
      },
      completion_date: "04 Mar 25 - 08:21:19 WIB",
      online_service_detail: {
        topic: "#37927 Konsultasi",
        request_deadline: "04 Mar 25 / -",
        tag: "Pemerintahan, Keuangan, Kemiskinan dan Ketimpangan, Produk Domestik Regional Bruto (Lapangan Usaha)",
        consulation_coverage: "Sulawesi Tengah",
        consultation_type: "Konsultasi Data",
        transaction_status: "Menunggu",
      },
    },
  },
  {
    transaction_id: "#7200-37884",
    customer_name: "AYU SAVITRI",
    need_type: "Konsultasi Kunjungan langsung",
    request_date: "2025-02-28",
    main_operator: "Ince Mariyani S.E., M.M.",
    status: "Selesai: 0",
    detail: {
      customer_detail: {
        name: "AYU SAVITRI",
        email: "savitria719@gmail.com",
        phone_gender: "085272922180/Perempuan",
        age_education: "22/<= SMA",
        unit: "Pribadi/Lainnya",
      },
      completion_date: "01 Maret 2025",
      onsite_visit_detail: {
        need_type: "Konsultasi",
        request_date: "28 Februari 2025",
        completion_date: "01 Maret 2025",
        operator: "Ince Mariyani S.E., M.M.",
        transaction_status: "selesai",
      },
    },
  },
  {
    transaction_id: "#7200-37875",
    customer_name: "ANNISA NABILA FEBRYANA",
    need_type: "Konsultasi Kunjungan langsung",
    request_date: "2025-02-28",
    main_operator: "Ince Mariyani S.E., M.M.",
    status: "Selesai: 5",
    detail: {
      customer_detail: {
        name: "ANNISA NABILA FEBRYANA",
        email: "annisanabilafebx@gmail.com",
        phone_gender: "085967262261/Perempuan",
        age_education: "22/<= SMA",
        unit: "Pribadi/Lainnya",
      },
      completion_date: "01 Maret 2025",
      onsite_visit_detail: {
        need_type: "Konsultasi",
        request_date: "28 Februari 2025",
        completion_date: "01 Maret 2025",
        operator: "Ince Mariyani S.E., M.M.",
        transaction_status: "selesai",
      },
    },
  },
  {
    transaction_id: "#7200-37806",
    customer_name: "ALCE PRICILIA",
    need_type: "Konsultasi Kunjungan langsung",
    request_date: "2025-02-26",
    main_operator: "Ince Mariyani S.E., M.M.",
    status: "Selesai: 0",
    detail: {
      customer_detail: {
        name: "ALCE PRICILIA",
        email: "alce.newlook@gmail.com",
        phone_gender: "081242243304/Perempuan",
        age_education: "27/S1",
        unit: "Pribadi/Lainnya",
      },
      completion_date: "27 Februari 2025",
      onsite_visit_detail: {
        need_type: "Konsultasi",
        request_date: "26 Februari 2025",
        completion_date: "27 Februari 2025",
        operator: "Ince Mariyani S.E., M.M.",
        transaction_status: "selesai",
      },
    },
  },
  {
    transaction_id: "#7200-37792",
    customer_name: "Grifit Parengkuan",
    need_type: "Konsultasi Kunjungan langsung",
    request_date: "2025-02-26",
    main_operator: "Ince Mariyani S.E., M.M.",
    status: "Selesai: 0",
    detail: {
      customer_detail: {
        name: "Grifit Parengkuan",
        email: "grifitp@gmail.com",
        phone_gender: "081143802211/Perempuan",
        age_education: "37/S2",
        unit: "Pegawai Tetap BPR Prisma Dana",
      },
      completion_date: "27 Februari 2025",
      onsite_visit_detail: {
        need_type: "Konsultasi",
        request_date: "26 Februari 2025",
        completion_date: "27 Februari 2025",
        operator: "Ince Mariyani S.E., M.M.",
        transaction_status: "selesai",
      },
    },
  },
  {
    transaction_id: "#7200-37581",
    customer_name: "Mahfudhoh Ulin",
    need_type: "Konsultasi Kunjungan langsung",
    request_date: "2025-02-19",
    main_operator: "Ince Mariyani S.E., M.M.",
    status: "Selesai: 0",
    detail: {
      customer_detail: {
        name: "Mahfudhoh Ulin",
        email: "mahfudhoh.nuha@pln.co.id",
        phone_gender: "081327788080/Perempuan",
        age_education: "24/S1",
        unit: "Pegawai Tetap PLN Area Palu",
      },
      completion_date: "20 Februari 2025",
      onsite_visit_detail: {
        need_type: "Konsultasi",
        request_date: "19 Februari 2025",
        completion_date: "20 Februari 2025",
        operator: "Ince Mariyani S.E., M.M.",
        transaction_status: "selesai",
      },
    },
  },
  {
    transaction_id: "#7200-37451",
    customer_name: "ADHIL",
    need_type: "Konsultasi Kunjungan langsung",
    request_date: "2025-02-13",
    main_operator: "Ince Mariyani S.E., M.M.",
    status: "Selesai: 0",
    detail: {
      customer_detail: {
        name: "ADHIL",
        email: "adhilputraa2003@gmail.com",
        phone_gender: "082254726945/Laki-laki",
        age_education: "22/<= SMA",
        unit: "Pribadi/Lainnya",
      },
      completion_date: "14 Februari 2025",
      onsite_visit_detail: {
        need_type: "Konsultasi",
        request_date: "13 Februari 2025",
        completion_date: "14 Februari 2025",
        operator: "Ince Mariyani S.E., M.M.",
        transaction_status: "selesai",
      },
    },
  },
  {
    transaction_id: "#7200-37450",
    customer_name: "RAFLI RAFF",
    need_type: "Konsultasi Kunjungan langsung",
    request_date: "2025-02-13",
    main_operator: "Ince Mariyani S.E., M.M.",
    status: "Selesai: 0",
    detail: {
      customer_detail: {
        name: "RAFLI RAFF",
        email: "rafliraff26@gmail.com",
        phone_gender: "085657208148/Laki-laki",
        age_education: "23/<= SMA",
        unit: "Pribadi/Lainnya",
      },
      completion_date: "14 Februari 2025",
      onsite_visit_detail: {
        need_type: "Konsultasi",
        request_date: "13 Februari 2025",
        completion_date: "14 Februari 2025",
        operator: "Ince Mariyani S.E., M.M.",
        transaction_status: "selesai",
      },
    },
  },
  {
    transaction_id: "#7200-37348",
    customer_name: "RINI",
    need_type: "Konsultasi Kunjungan langsung",
    request_date: "2025-02-11",
    main_operator: "Ince Mariyani S.E., M.M.",
    status: "Selesai: 0",
    detail: {
      customer_detail: {
        name: "RINI",
        email: "fadillahrini690@gmail.com",
        phone_gender: "081523920959/Perempuan",
        age_education: "23/<= SMA",
        unit: "Pribadi/Lainnya",
      },
      completion_date: "12 Februari 2025",
      onsite_visit_detail: {
        need_type: "Konsultasi",
        request_date: "11 Februari 2025",
        completion_date: "12 Februari 2025",
        operator: "Ince Mariyani S.E., M.M.",
        transaction_status: "selesai",
      },
    },
  },
  {
    transaction_id: "#7200-37224",
    customer_name: "RIRIN SURYA NINGSIH",
    need_type: "Konsultasi Kunjungan langsung",
    request_date: "2025-02-06",
    main_operator: "Ince Mariyani S.E., M.M.",
    status: "Selesai: 0",
    detail: {
      customer_detail: {
        name: "RIRIN SURYA NINGSIH",
        email: "ririnsuryaningsih13@gmail.com",
        phone_gender: "085823718575/Perempuan",
        age_education: "22/<= SMA",
        unit: "Pribadi/Lainnya",
      },
      completion_date: "07 Februari 2025",
      onsite_visit_detail: {
        need_type: "Konsultasi",
        request_date: "06 Februari 2025",
        completion_date: "07 Februari 2025",
        operator: "Ince Mariyani S.E., M.M.",
        transaction_status: "selesai",
      },
    },
  },
  {
    transaction_id: "#7200-37223",
    customer_name: "RIRIN SURYA NINGSIH",
    need_type: "Konsultasi Kunjungan langsung",
    request_date: "2025-02-06",
    main_operator: "Ince Mariyani S.E., M.M.",
    status: "Selesai: 0",
    detail: {
      customer_detail: {
        name: "RIRIN SURYA NINGSIH",
        email: "ririnsuryaningsih13@gmail.com",
        phone_gender: "085823718575/Perempuan",
        age_education: "22/<= SMA",
        unit: "Pribadi/Lainnya",
      },
      completion_date: "07 Februari 2025",
      onsite_visit_detail: {
        need_type: "Konsultasi",
        request_date: "06 Februari 2025",
        completion_date: "07 Februari 2025",
        operator: "Ince Mariyani S.E., M.M.",
        transaction_status: "selesai",
      },
    },
  },
  {
    transaction_id: "#7200-37192",
    customer_name: "NI KOMANG SITI PARWAH",
    need_type: "Konsultasi Kunjungan langsung",
    request_date: "2025-02-05",
    main_operator: "Ince Mariyani S.E., M.M.",
    status: "Selesai: 5",
    detail: {
      customer_detail: {
        name: "NI KOMANG SITI PARWAH",
        email: "sitiparwati93@gmail.com",
        phone_gender: "082239712248/Perempuan",
        age_education: "21/<= SMA",
        unit: "Pribadi/Lainnya",
      },
      completion_date: "06 Februari 2025",
      onsite_visit_detail: {
        need_type: "Konsultasi",
        request_date: "05 Februari 2025",
        completion_date: "06 Februari 2025",
        operator: "Ince Mariyani S.E., M.M.",
        transaction_status: "selesai",
      },
    },
  },
  {
    transaction_id: "#7200-37191",
    customer_name: "NI KOMANG SITI PARWAH",
    need_type: "Konsultasi Kunjungan langsung",
    request_date: "2025-02-05",
    main_operator: "Ince Mariyani S.E., M.M.",
    status: "Selesai: 5",
    detail: {
      customer_detail: {
        name: "NI KOMANG SITI PARWAH",
        email: "sitiparwati93@gmail.com",
        phone_gender: "082239712248/Perempuan",
        age_education: "21/<= SMA",
        unit: "Pribadi/Lainnya",
      },
      completion_date: "06 Februari 2025",
      onsite_visit_detail: {
        need_type: "Konsultasi",
        request_date: "05 Februari 2025",
        completion_date: "06 Februari 2025",
        operator: "Ince Mariyani S.E., M.M.",
        transaction_status: "selesai",
      },
    },
  },
  {
    transaction_id: "#7200-37178",
    customer_name: "DARUSY SHAHADAH",
    need_type: "Konsultasi Kunjungan langsung",
    request_date: "2025-02-05",
    main_operator: "Ince Mariyani S.E., M.M.",
    status: "Selesai: 0",
    detail: {
      customer_detail: {
        name: "DARUSY SHAHADAH",
        email: "darusyshahadah03@gmail.com",
        phone_gender: "082292651312/Perempuan",
        age_education: "23/<= SMA",
        unit: "Pribadi/Lainnya",
      },
      completion_date: "06 Februari 2025",
      onsite_visit_detail: {
        need_type: "Konsultasi",
        request_date: "05 Februari 2025",
        completion_date: "06 Februari 2025",
        operator: "Ince Mariyani S.E., M.M.",
        transaction_status: "selesai",
      },
    },
  },
  {
    transaction_id: "#7200-37176",
    customer_name: "NUR FADILAH",
    need_type: "Konsultasi Kunjungan langsung",
    request_date: "2025-02-05",
    main_operator: "Ince Mariyani S.E., M.M.",
    status: "Selesai: 0",
    detail: {
      customer_detail: {
        name: "NUR FADILAH",
        email: "dillaf031@gmail.com",
        phone_gender: "085399790474/Perempuan",
        age_education: "22/<= SMA",
        unit: "Pribadi/Lainnya",
      },
      completion_date: "06 Februari 2025",
      onsite_visit_detail: {
        need_type: "Konsultasi",
        request_date: "05 Februari 2025",
        completion_date: "06 Februari 2025",
        operator: "Ince Mariyani S.E., M.M.",
        transaction_status: "selesai",
      },
    },
  },
  {
    transaction_id: "#7200-37174",
    customer_name: "ANISA SEPTIANI",
    need_type: "Konsultasi Kunjungan langsung",
    request_date: "2025-02-05",
    main_operator: "Ince Mariyani S.E., M.M.",
    status: "Selesai: 0",
    detail: {
      customer_detail: {
        name: "ANISA SEPTIANI",
        email: "septianianisa@gmail.com",
        phone_gender: "085823571457/Perempuan",
        age_education: "23/<= SMA",
        unit: "Pribadi/Lainnya",
      },
      completion_date: "06 Februari 2025",
      onsite_visit_detail: {
        need_type: "Konsultasi",
        request_date: "05 Februari 2025",
        completion_date: "06 Februari 2025",
        operator: "Ince Mariyani S.E., M.M.",
        transaction_status: "selesai",
      },
    },
  },
  {
    transaction_id: "#7200-37129",
    customer_name: "NURLINA",
    need_type: "Konsultasi Kunjungan langsung",
    request_date: "2025-02-04",
    main_operator: "Ince Mariyani S.E., M.M.",
    status: "Selesai: 0",
    detail: {
      customer_detail: {
        name: "NURLINA",
        email: "nl839427@gmail.com",
        phone_gender: "082259757689/Perempuan",
        age_education: "22/<= SMA",
        unit: "Pribadi/Lainnya",
      },
      completion_date: "05 Februari 2025",
      onsite_visit_detail: {
        need_type: "Konsultasi",
        request_date: "04 Februari 2025",
        completion_date: "05 Februari 2025",
        operator: "Ince Mariyani S.E., M.M.",
        transaction_status: "selesai",
      },
    },
  },
  {
    transaction_id: "#7200-37076",
    customer_name: "RENO ADE BUDIARJO",
    need_type: "Konsultasi Kunjungan langsung",
    request_date: "2025-01-31",
    main_operator: "Ince Mariyani S.E., M.M.",
    status: "Selesai: 0",
    detail: {
      customer_detail: {
        name: "RENO ADE BUDIARJO",
        email: "renobudiardjo1@gmail.com",
        phone_gender: "082315555899/Laki-laki",
        age_education: "38/S1",
        unit: "Staf Dinas Kelautan Dan Perikanan Provinsi Sulawesi Tengah",
      },
      completion_date: "01 Februari 2025",
      onsite_visit_detail: {
        need_type: "Konsultasi",
        request_date: "31 Januari 2025",
        completion_date: "01 Februari 2025",
        operator: "Ince Mariyani S.E., M.M.",
        transaction_status: "selesai",
      },
    },
  },
  {
    transaction_id: "#7200-36973",
    customer_name: "NI PUTU PUSPITA IKA DEWI",
    need_type: "Konsultasi Kunjungan langsung",
    request_date: "2025-01-24",
    main_operator: "Ince Mariyani S.E., M.M.",
    status: "Selesai: 0",
    detail: {
      customer_detail: {
        name: "NI PUTU PUSPITA IKA DEWI",
        email: "niputupuspitaikadewi@gmail.com",
        phone_gender: "082292487520/Perempuan",
        age_education: "22/<= SMA",
        unit: "Pribadi/Lainnya",
      },
      completion_date: "25 Januari 2025",
      onsite_visit_detail: {
        need_type: "Konsultasi",
        request_date: "24 Januari 2025",
        completion_date: "25 Januari 2025",
        operator: "Ince Mariyani S.E., M.M.",
        transaction_status: "selesai",
      },
    },
  },
  {
    transaction_id: "#7200-36899",
    customer_name: "NUR SALSABILA",
    need_type: "Konsultasi Kunjungan langsung",
    request_date: "2025-01-22",
    main_operator: "Ince Mariyani S.E., M.M.",
    status: "Selesai: 0",
    detail: {
      customer_detail: {
        name: "NUR SALSABILA",
        email: "nursalsabilah662317@gmail.com",
        phone_gender: "081242672417/Perempuan",
        age_education: "22/<= SMA",
        unit: "Pribadi/Lainnya",
      },
      completion_date: "23 Januari 2025",
      onsite_visit_detail: {
        need_type: "Konsultasi",
        request_date: "22 Januari 2025",
        completion_date: "23 Januari 2025",
        operator: "Ince Mariyani S.E., M.M.",
        transaction_status: "selesai",
      },
    },
  },
  {
    transaction_id: "#7200-36898",
    customer_name: "SITI ANISA",
    need_type: "Konsultasi Kunjungan langsung",
    request_date: "2025-01-22",
    main_operator: "Ince Mariyani S.E., M.M.",
    status: "Selesai: 0",
    detail: {
      customer_detail: {
        name: "SITI ANISA",
        email: "annisaichaa1610@gmail.com",
        phone_gender: "082349399975/Perempuan",
        age_education: "23/<= SMA",
        unit: "Pribadi/Lainnya",
      },
      completion_date: "23 Januari 2025",
      onsite_visit_detail: {
        need_type: "Konsultasi",
        request_date: "22 Januari 2025",
        completion_date: "23 Januari 2025",
        operator: "Ince Mariyani S.E., M.M.",
        transaction_status: "selesai",
      },
    },
  },
  {
    transaction_id: "#7200-36886",
    customer_name: "MUTMAINNAH",
    need_type: "Konsultasi Kunjungan langsung",
    request_date: "2025-01-22",
    main_operator: "Ince Mariyani S.E., M.M.",
    status: "Selesai: 0",
    detail: {
      customer_detail: {
        name: "MUTMAINNAH",
        email: "mutmainnahpanga26@gmail.com",
        phone_gender: "082335252212/Perempuan",
        age_education: "22/<= SMA",
        unit: "Pribadi/Lainnya",
      },
      completion_date: "23 Januari 2025",
      onsite_visit_detail: {
        need_type: "Konsultasi",
        request_date: "22 Januari 2025",
        completion_date: "23 Januari 2025",
        operator: "Ince Mariyani S.E., M.M.",
        transaction_status: "selesai",
      },
    },
  },
  {
    transaction_id: "#7200-36885",
    customer_name: "SHEHERAZADE",
    need_type: "Konsultasi Kunjungan langsung",
    request_date: "2025-01-22",
    main_operator: "Ince Mariyani S.E., M.M.",
    status: "Selesai: 0",
    detail: {
      customer_detail: {
        name: "SHEHERAZADE",
        email: "s.sheherazade@berheles.edu",
        phone_gender: "081295653294/Perempuan",
        age_education: "32/S2",
        unit: "Pribadi/Lainnya",
      },
      completion_date: "23 Januari 2025",
      onsite_visit_detail: {
        need_type: "Konsultasi",
        request_date: "22 Januari 2025",
        completion_date: "23 Januari 2025",
        operator: "Ince Mariyani S.E., M.M.",
        transaction_status: "selesai",
      },
    },
  },
  {
    transaction_id: "#7200-36858",
    customer_name: "FADILAH SALSABILA",
    need_type: "Konsultasi Kunjungan langsung",
    request_date: "2025-01-21",
    main_operator: "Ince Mariyani S.E., M.M.",
    status: "Selesai: 0",
    detail: {
      customer_detail: {
        name: "FADILAH SALSABILA",
        email: "fadilah.salsabila@icloud.com",
        phone_gender: "085967182103/Perempuan",
        age_education: "23/<= SMA",
        unit: "Pribadi/Lainnya",
      },
      completion_date: "22 Januari 2025",
      onsite_visit_detail: {
        need_type: "Konsultasi",
        request_date: "21 Januari 2025",
        completion_date: "22 Januari 2025",
        operator: "Ince Mariyani S.E., M.M.",
        transaction_status: "selesai",
      },
    },
  },
  {
    transaction_id: "#7200-36844",
    customer_name: "MOH AKSAY",
    need_type: "Konsultasi Kunjungan langsung",
    request_date: "2025-01-21",
    main_operator: "Ince Mariyani S.E., M.M.",
    status: "Selesai: 0",
    detail: {
      customer_detail: {
        name: "MOH AKSAY",
        email: "aksaypratama12@gmail.com",
        phone_gender: "085796789916/Laki-laki",
        age_education: "21/<= SMA",
        unit: "Pribadi/Lainnya",
      },
      completion_date: "22 Januari 2025",
      onsite_visit_detail: {
        need_type: "Konsultasi",
        request_date: "21 Januari 2025",
        completion_date: "22 Januari 2025",
        operator: "Ince Mariyani S.E., M.M.",
        transaction_status: "selesai",
      },
    },
  },
  {
    transaction_id: "#7200-36834",
    customer_name: "EMMA T POMBILE",
    need_type: "Konsultasi Kunjungan langsung",
    request_date: "2025-01-21",
    main_operator: "Ince Mariyani S.E., M.M.",
    status: "Selesai: 0",
    detail: {
      customer_detail: {
        name: "EMMA T POMBILE",
        email: "tititowinaloa@gmail.com",
        phone_gender: "087777443812/Perempuan",
        age_education: "22/<= SMA",
        unit: "Pribadi/Lainnya",
      },
      completion_date: "22 Januari 2025",
      onsite_visit_detail: {
        need_type: "Konsultasi",
        request_date: "21 Januari 2025",
        completion_date: "22 Januari 2025",
        operator: "Ince Mariyani S.E., M.M.",
        transaction_status: "selesai",
      },
    },
  },
  {
    transaction_id: "#7200-36809",
    customer_name: "Aditya Saputra",
    need_type: "Konsultasi Layanan Online",
    request_date: "2025-01-20",
    main_operator: "Bahtiar SST",
    status: "Selesai: 5",
    detail: {
      customer_detail: {
        name: "Aditya Saputra",
        email: "aditsaputr8@gmail.com",
        phone_gender: "33 Tahun/Laki-laki",
        consumer_segmentation: "Instansi/Lembaga Pemerintah (Pusat/Daerah)",
        country_phone: "ID/081218082812",
        average_rating: "5.00",
      },
      completion_date: "20 Jan 25 - 13:12:48 WIB",
      online_service_detail: {
        topic: "#36809 Konsultasi",
        request_deadline: "20 Jan 25 / 30 Jan 25",
        tag: "Peternakan",
        consulation_coverage: "Sulawesi Tengah",
        consultation_type: "Konsultasi Data",
        operator: "Bahtiar SST",
        transaction_status: "Selesai",
      },
    },
  },
  {
    transaction_id: "#7200-36474",
    customer_name: "Wahyu Zuli Firmanto",
    need_type: "Permintaan Data Layanan Online",
    request_date: "2025-01-08",
    main_operator: "Bahtiar SST",
    status: "Selesai: 5",
    detail: {
      customer_detail: {},
      completion_date: "08 Jan 25 - 16:55:13 WIB",
      online_service_detail: {},
    },
  },
  {
    transaction_id: "#7200-36306",
    customer_name: "Fikran",
    need_type: "Konsultasi Kunjungan langsung",
    request_date: "2025-01-02",
    main_operator: "Ince Mariyani S.E., M.M.",
    status: "Selesai: 0",
    detail: {
      customer_detail: {
        name: "Fikran",
        email: "fikran545@gmail.com",
        phone_gender: "085242579181/Laki-laki",
        age_education: "23/<= SMA",
        unit: "Pribadi/Lainnya",
      },
      completion_date: "03 Januari 2025",
      onsite_visit_detail: {
        need_type: "Konsultasi",
        request_date: "02 Januari 2025",
        completion_date: "03 Januari 2025",
        operator: "Ince Mariyani S.E., M.M.",
        transaction_status: "selesai",
      },
    },
  },
];
