export const consultationData = [
  {
    id_transaksi: "#7200-41090",
    nama_konsumen: "Pegawai Teladan",
    email_konsumen: "tiarsidik@bps.go.id",
    jenis_keperluan: "Konsultasi",
    keperluan_lain: "Kunjungan langsung",
    status: "",
    tanggal_permintaan: "2025-07-16",
    tanggal_selesai: "",
    operator: "Bahtiar SST",
  },
  {
    id_transaksi: "#7200-41013",
    nama_konsumen: "LESMANA",
    email_konsumen: "lesmanalewis71@gmail.com",
    jenis_keperluan: "Konsultasi",
    keperluan_lain: "Kunjungan langsung",
    status: "Selesai",
    tanggal_permintaan: "2025-07-14",
    tanggal_selesai: "",
    operator: "Ince Mariyani S.E., M.M.",
  },
  {
    id_transaksi: "#7200-41011",
    nama_konsumen: "YULFIANA",
    email_konsumen: "yuullfianaaa@gmail.com",
    jenis_keperluan: "Konsultasi",
    keperluan_lain: "Kunjungan langsung",
    status: "Selesai",
    tanggal_permintaan: "2025-07-14",
    tanggal_selesai: "",
    operator: "Ince Mariyani S.E., M.M.",
  },
  {
    id_transaksi: "#7200-41007",
    nama_konsumen: "YULFIANA",
    email_konsumen: "yuullfianaa@gmail.com",
    jenis_keperluan: "Konsultasi",
    keperluan_lain: "Kunjungan langsung",
    status: "Selesai",
    tanggal_permintaan: "2025-07-14",
    tanggal_selesai: "",
    operator: "Ince Mariyani S.E., M.M.",
  },
  {
    id_transaksi: "#7200-40838",
    nama_konsumen: "TONNO MELANGI",
    email_konsumen: "tonnomelangi829@gmail.com",
    jenis_keperluan: "Konsultasi",
    keperluan_lain: "Kunjungan langsung",
    status: "Selesai",
    tanggal_permintaan: "2025-07-07",
    tanggal_selesai: "",
    operator: "Ince Mariyani S.E., M.M.",
  },
  {
    id_transaksi: "#7200-40748",
    nama_konsumen: "RICARDO ANTHONIE",
    email_konsumen: "richardo.anthonie@gmail.com",
    jenis_keperluan: "Konsultasi",
    keperluan_lain: "Kunjungan langsung",
    status: "Selesai",
    tanggal_permintaan: "2025-07-02",
    tanggal_selesai: "",
    operator: "Ince Mariyani S.E., M.M.",
  },
  {
    id_transaksi: "#7200-40746",
    nama_konsumen: "ISNAINI AL. QUR'ANA",
    email_konsumen: "alquranaisnaini@gmail.com",
    jenis_keperluan: "Konsultasi",
    keperluan_lain: "Kunjungan langsung",
    status: "Selesai",
    tanggal_permintaan: "2025-07-02",
    tanggal_selesai: "",
    operator: "Ince Mariyani S.E., M.M.",
  },
  {
    id_transaksi: "#7200-40629",
    nama_konsumen: "Wahyu Zuli Firmanto",
    email_konsumen: "wahyu@u.nus.edu",
    jenis_keperluan: "Permintaan Data",
    keperluan_lain: "Layanan Online",
    status: "Selesai",
    tanggal_permintaan: "2025-06-26",
    tanggal_selesai: "",
    operator: "Bahtiar SST",
  },
  {
    id_transaksi: "#7200-40563",
    nama_konsumen: "MOH. WAHYU DWI AGUNG",
    email_konsumen: "wahyudwiagung002@gmail.com",
    jenis_keperluan: "Konsultasi",
    keperluan_lain: "Kunjungan langsung",
    status: "Selesai",
    tanggal_permintaan: "2025-06-24",
    tanggal_selesai: "",
    operator: "Ince Mariyani S.E., M.M.",
  },
  {
    id_transaksi: "#7200-40540",
    nama_konsumen: "Nareswari",
    email_konsumen: "nareswarinh9d@gmail.com",
    jenis_keperluan: "Konsultasi",
    keperluan_lain: "Layanan Online",
    status: "Selesai",
    tanggal_permintaan: "2025-06-23",
    tanggal_selesai: "",
    operator: "Bahtiar SST",
  },
  {
    id_transaksi: "#7200-41090",
    nama_konsumen: "Pegawai Teladan",
    email_konsumen: "tiarsidik@bps.go.id",
    jenis_keperluan: "Konsultasi",
    keperluan_lain: "Kunjungan langsung",
    status: "",
    tanggal_permintaan: "2025-07-16",
    tanggal_selesai: "",
    operator: "Bahtiar SST",
  },
  {
    id_transaksi: "#7200-41013",
    nama_konsumen: "LESMANA",
    email_konsumen: "lesmanalewis71@gmail.com",
    jenis_keperluan: "Konsultasi",
    keperluan_lain: "Kunjungan langsung",
    status: "Selesai",
    tanggal_permintaan: "2025-07-14",
    tanggal_selesai: "",
    operator: "Ince Mariyani S.E., M.M.",
  },
  {
    id_transaksi: "#7200-41011",
    nama_konsumen: "YULFIANA",
    email_konsumen: "yuullfianaaa@gmail.com",
    jenis_keperluan: "Konsultasi",
    keperluan_lain: "Kunjungan langsung",
    status: "Selesai",
    tanggal_permintaan: "2025-07-14",
    tanggal_selesai: "",
    operator: "Ince Mariyani S.E., M.M.",
  },
  {
    id_transaksi: "#7200-41007",
    nama_konsumen: "YULFIANA",
    email_konsumen: "yuullfianaa@gmail.com",
    jenis_keperluan: "Konsultasi",
    keperluan_lain: "Kunjungan langsung",
    status: "Selesai",
    tanggal_permintaan: "2025-07-14",
    tanggal_selesai: "",
    operator: "Ince Mariyani S.E., M.M.",
  },
  {
    id_transaksi: "#7200-40838",
    nama_konsumen: "TONNO MELANGI",
    email_konsumen: "tonnomelangi829@gmail.com",
    jenis_keperluan: "Konsultasi",
    keperluan_lain: "Kunjungan langsung",
    status: "Selesai",
    tanggal_permintaan: "2025-07-07",
    tanggal_selesai: "",
    operator: "Ince Mariyani S.E., M.M.",
  },
  {
    id_transaksi: "#7200-40748",
    nama_konsumen: "RICARDO ANTHONIE",
    email_konsumen: "richardo.anthonie@gmail.com",
    jenis_keperluan: "Konsultasi",
    keperluan_lain: "Kunjungan langsung",
    status: "Selesai",
    tanggal_permintaan: "2025-07-02",
    tanggal_selesai: "",
    operator: "Ince Mariyani S.E., M.M.",
  },
  {
    id_transaksi: "#7200-40746",
    nama_konsumen: "ISNAINI AL. QUR'ANA",
    email_konsumen: "alquranaisnaini@gmail.com",
    jenis_keperluan: "Konsultasi",
    keperluan_lain: "Kunjungan langsung",
    status: "Selesai",
    tanggal_permintaan: "2025-07-02",
    tanggal_selesai: "",
    operator: "Ince Mariyani S.E., M.M.",
  },
  {
    id_transaksi: "#7200-40629",
    nama_konsumen: "Wahyu Zuli Firmanto",
    email_konsumen: "wahyu@u.nus.edu",
    jenis_keperluan: "Permintaan Data",
    keperluan_lain: "Layanan Online",
    status: "Selesai",
    tanggal_permintaan: "2025-06-26",
    tanggal_selesai: "",
    operator: "Bahtiar SST",
  },
  {
    id_transaksi: "#7200-40563",
    nama_konsumen: "MOH. WAHYU DWI AGUNG",
    email_konsumen: "wahyudwiagung002@gmail.com",
    jenis_keperluan: "Konsultasi",
    keperluan_lain: "Kunjungan langsung",
    status: "Selesai",
    tanggal_permintaan: "2025-06-24",
    tanggal_selesai: "",
    operator: "Ince Mariyani S.E., M.M.",
  },
  {
    id_transaksi: "#7200-40540",
    nama_konsumen: "Nareswari",
    email_konsumen: "nareswarinh9d@gmail.com",
    jenis_keperluan: "Konsultasi",
    keperluan_lain: "Layanan Online",
    status: "Selesai",
    tanggal_permintaan: "2025-06-23",
    tanggal_selesai: "",
    operator: "Bahtiar SST",
  },
  {
    id_transaksi: "#7200-41090",
    nama_konsumen: "Pegawai Teladan",
    email_konsumen: "tiarsidik@bps.go.id",
    jenis_keperluan: "Konsultasi",
    keperluan_lain: "Kunjungan langsung",
    status: "",
    tanggal_permintaan: "2025-07-16",
    tanggal_selesai: "",
    operator: "Bahtiar SST",
  },
  {
    id_transaksi: "#7200-41013",
    nama_konsumen: "LESMANA",
    email_konsumen: "lesmanalewis71@gmail.com",
    jenis_keperluan: "Konsultasi",
    keperluan_lain: "Kunjungan langsung",
    status: "Selesai",
    tanggal_permintaan: "2025-07-14",
    tanggal_selesai: "",
    operator: "Ince Mariyani S.E., M.M.",
  },
  {
    id_transaksi: "#7200-41011",
    nama_konsumen: "YULFIANA",
    email_konsumen: "yuullfianaaa@gmail.com",
    jenis_keperluan: "Konsultasi",
    keperluan_lain: "Kunjungan langsung",
    status: "Selesai",
    tanggal_permintaan: "2025-07-14",
    tanggal_selesai: "",
    operator: "Ince Mariyani S.E., M.M.",
  },
  {
    id_transaksi: "#7200-41007",
    nama_konsumen: "YULFIANA",
    email_konsumen: "yuullfianaa@gmail.com",
    jenis_keperluan: "Konsultasi",
    keperluan_lain: "Kunjungan langsung",
    status: "Selesai",
    tanggal_permintaan: "2025-07-14",
    tanggal_selesai: "",
    operator: "Ince Mariyani S.E., M.M.",
  },
  {
    id_transaksi: "#7200-40838",
    nama_konsumen: "TONNO MELANGI",
    email_konsumen: "tonnomelangi829@gmail.com",
    jenis_keperluan: "Konsultasi",
    keperluan_lain: "Kunjungan langsung",
    status: "Selesai",
    tanggal_permintaan: "2025-07-07",
    tanggal_selesai: "",
    operator: "Ince Mariyani S.E., M.M.",
  },
  {
    id_transaksi: "#7200-40748",
    nama_konsumen: "RICARDO ANTHONIE",
    email_konsumen: "richardo.anthonie@gmail.com",
    jenis_keperluan: "Konsultasi",
    keperluan_lain: "Kunjungan langsung",
    status: "Selesai",
    tanggal_permintaan: "2025-07-02",
    tanggal_selesai: "",
    operator: "Ince Mariyani S.E., M.M.",
  },
  {
    id_transaksi: "#7200-40746",
    nama_konsumen: "ISNAINI AL. QUR'ANA",
    email_konsumen: "alquranaisnaini@gmail.com",
    jenis_keperluan: "Konsultasi",
    keperluan_lain: "Kunjungan langsung",
    status: "Selesai",
    tanggal_permintaan: "2025-07-02",
    tanggal_selesai: "",
    operator: "Ince Mariyani S.E., M.M.",
  },
  {
    id_transaksi: "#7200-40629",
    nama_konsumen: "Wahyu Zuli Firmanto",
    email_konsumen: "wahyu@u.nus.edu",
    jenis_keperluan: "Permintaan Data",
    keperluan_lain: "Layanan Online",
    status: "Selesai",
    tanggal_permintaan: "2025-06-26",
    tanggal_selesai: "",
    operator: "Bahtiar SST",
  },
  {
    id_transaksi: "#7200-40563",
    nama_konsumen: "MOH. WAHYU DWI AGUNG",
    email_konsumen: "wahyudwiagung002@gmail.com",
    jenis_keperluan: "Konsultasi",
    keperluan_lain: "Kunjungan langsung",
    status: "Selesai",
    tanggal_permintaan: "2025-06-24",
    tanggal_selesai: "",
    operator: "Ince Mariyani S.E., M.M.",
  },
  {
    id_transaksi: "#7200-40540",
    nama_konsumen: "Nareswari",
    email_konsumen: "nareswarinh9d@gmail.com",
    jenis_keperluan: "Konsultasi",
    keperluan_lain: "Layanan Online",
    status: "Selesai",
    tanggal_permintaan: "2025-06-23",
    tanggal_selesai: "",
    operator: "Bahtiar SST",
  },
  {
    id_transaksi: "#7200-41090",
    nama_konsumen: "Pegawai Teladan",
    email_konsumen: "tiarsidik@bps.go.id",
    jenis_keperluan: "Konsultasi",
    keperluan_lain: "Kunjungan langsung",
    status: "Selesai",
    tanggal_permintaan: "2025-07-16",
    tanggal_selesai: "",
    operator: "Bahtiar SST",
  },
  {
    id_transaksi: "#7200-41013",
    nama_konsumen: "LESMANA",
    email_konsumen: "lesmanalewis71@gmail.com",
    jenis_keperluan: "Konsultasi",
    keperluan_lain: "Kunjungan langsung",
    status: "Selesai",
    tanggal_permintaan: "2025-07-14",
    tanggal_selesai: "",
    operator: "Ince Mariyani S.E., M.M.",
  },
  {
    id_transaksi: "#7200-41011",
    nama_konsumen: "YULFIANA",
    email_konsumen: "yuullfianaaa@gmail.com",
    jenis_keperluan: "Konsultasi",
    keperluan_lain: "Kunjungan langsung",
    status: "Selesai",
    tanggal_permintaan: "2025-07-14",
    tanggal_selesai: "",
    operator: "Ince Mariyani S.E., M.M.",
  },
  {
    id_transaksi: "#7200-41007",
    nama_konsumen: "YULFIANA",
    email_konsumen: "yuullfianaa@gmail.com",
    jenis_keperluan: "Konsultasi",
    keperluan_lain: "Kunjungan langsung",
    status: "Selesai",
    tanggal_permintaan: "2025-07-14",
    tanggal_selesai: "",
    operator: "Ince Mariyani S.E., M.M.",
  },
  {
    id_transaksi: "#7200-40838",
    nama_konsumen: "TONNO MELANGI",
    email_konsumen: "tonnomelangi829@gmail.com",
    jenis_keperluan: "Konsultasi",
    keperluan_lain: "Kunjungan langsung",
    status: "Selesai",
    tanggal_permintaan: "2025-07-07",
    tanggal_selesai: "",
    operator: "Ince Mariyani S.E., M.M.",
  },
  {
    id_transaksi: "#7200-40748",
    nama_konsumen: "RICARDO ANTHONIE",
    email_konsumen: "richardo.anthonie@gmail.com",
    jenis_keperluan: "Konsultasi",
    keperluan_lain: "Kunjungan langsung",
    status: "Selesai",
    tanggal_permintaan: "2025-07-02",
    tanggal_selesai: "",
    operator: "Ince Mariyani S.E., M.M.",
  },
  {
    id_transaksi: "#7200-40746",
    nama_konsumen: "ISNAINI AL. QUR'ANA",
    email_konsumen: "alquranaisnaini@gmail.com",
    jenis_keperluan: "Konsultasi",
    keperluan_lain: "Kunjungan langsung",
    status: "Selesai",
    tanggal_permintaan: "2025-07-02",
    tanggal_selesai: "",
    operator: "Ince Mariyani S.E., M.M.",
  },
  {
    id_transaksi: "#7200-40629",
    nama_konsumen: "Wahyu Zuli Firmanto",
    email_konsumen: "wahyu@u.nus.edu",
    jenis_keperluan: "Permintaan Data",
    keperluan_lain: "Layanan Online",
    status: "Selesai",
    tanggal_permintaan: "2025-06-26",
    tanggal_selesai: "",
    operator: "Bahtiar SST",
  },
  {
    id_transaksi: "#7200-40563",
    nama_konsumen: "MOH. WAHYU DWI AGUNG",
    email_konsumen: "wahyudwiagung002@gmail.com",
    jenis_keperluan: "Konsultasi",
    keperluan_lain: "Kunjungan langsung",
    status: "Selesai",
    tanggal_permintaan: "2025-06-24",
    tanggal_selesai: "",
    operator: "Ince Mariyani S.E., M.M.",
  },
  {
    id_transaksi: "#7200-40540",
    nama_konsumen: "Nareswari",
    email_konsumen: "nareswarinh9d@gmail.com",
    jenis_keperluan: "Konsultasi",
    keperluan_lain: "Layanan Online",
    status: "Selesai",
    tanggal_permintaan: "2025-06-23",
    tanggal_selesai: "",
    operator: "Bahtiar SST",
  },
  {
    id_transaksi: "#7200-41090",
    nama_konsumen: "Pegawai Teladan",
    email_konsumen: "tiarsidik@bps.go.id",
    jenis_keperluan: "Konsultasi",
    keperluan_lain: "Kunjungan langsung",
    status: "Selesai",
    tanggal_permintaan: "2025-07-16",
    tanggal_selesai: "",
    operator: "Bahtiar SST",
  },
  {
    id_transaksi: "#7200-41013",
    nama_konsumen: "LESMANA",
    email_konsumen: "lesmanalewis71@gmail.com",
    jenis_keperluan: "Konsultasi",
    keperluan_lain: "Kunjungan langsung",
    status: "Selesai",
    tanggal_permintaan: "2025-07-14",
    tanggal_selesai: "",
    operator: "Ince Mariyani S.E., M.M.",
  },
  {
    id_transaksi: "#7200-41011",
    nama_konsumen: "YULFIANA",
    email_konsumen: "yuullfianaaa@gmail.com",
    jenis_keperluan: "Konsultasi",
    keperluan_lain: "Kunjungan langsung",
    status: "Selesai",
    tanggal_permintaan: "2025-07-14",
    tanggal_selesai: "",
    operator: "Ince Mariyani S.E., M.M.",
  },
  {
    id_transaksi: "#7200-41007",
    nama_konsumen: "YULFIANA",
    email_konsumen: "yuullfianaa@gmail.com",
    jenis_keperluan: "Konsultasi",
    keperluan_lain: "Kunjungan langsung",
    status: "Selesai",
    tanggal_permintaan: "2025-07-14",
    tanggal_selesai: "",
    operator: "Ince Mariyani S.E., M.M.",
  },
  {
    id_transaksi: "#7200-40838",
    nama_konsumen: "TONNO MELANGI",
    email_konsumen: "tonnomelangi829@gmail.com",
    jenis_keperluan: "Konsultasi",
    keperluan_lain: "Kunjungan langsung",
    status: "Selesai",
    tanggal_permintaan: "2025-07-07",
    tanggal_selesai: "",
    operator: "Ince Mariyani S.E., M.M.",
  },
  {
    id_transaksi: "#7200-40748",
    nama_konsumen: "RICARDO ANTHONIE",
    email_konsumen: "richardo.anthonie@gmail.com",
    jenis_keperluan: "Konsultasi",
    keperluan_lain: "Kunjungan langsung",
    status: "Selesai",
    tanggal_permintaan: "2025-07-02",
    tanggal_selesai: "",
    operator: "Ince Mariyani S.E., M.M.",
  },
  {
    id_transaksi: "#7200-40746",
    nama_konsumen: "ISNAINI AL. QUR'ANA",
    email_konsumen: "alquranaisnaini@gmail.com",
    jenis_keperluan: "Konsultasi",
    keperluan_lain: "Kunjungan langsung",
    status: "Selesai",
    tanggal_permintaan: "2025-07-02",
    tanggal_selesai: "",
    operator: "Ince Mariyani S.E., M.M.",
  },
  {
    id_transaksi: "#7200-40629",
    nama_konsumen: "Wahyu Zuli Firmanto",
    email_konsumen: "wahyu@u.nus.edu",
    jenis_keperluan: "Permintaan Data",
    keperluan_lain: "Layanan Online",
    status: "Selesai",
    tanggal_permintaan: "2025-06-26",
    tanggal_selesai: "",
    operator: "Bahtiar SST",
  },
  {
    id_transaksi: "#7200-40563",
    nama_konsumen: "MOH. WAHYU DWI AGUNG",
    email_konsumen: "wahyudwiagung002@gmail.com",
    jenis_keperluan: "Konsultasi",
    keperluan_lain: "Kunjungan langsung",
    status: "Selesai",
    tanggal_permintaan: "2025-06-24",
    tanggal_selesai: "",
    operator: "Ince Mariyani S.E., M.M.",
  },
  {
    id_transaksi: "#7200-40540",
    nama_konsumen: "Nareswari",
    email_konsumen: "nareswarinh9d@gmail.com",
    jenis_keperluan: "Konsultasi",
    keperluan_lain: "Layanan Online",
    status: "Selesai",
    tanggal_permintaan: "2025-06-23",
    tanggal_selesai: "",
    operator: "Bahtiar SST",
  },
];
